apiVersion: v1
kind: Service
metadata:
  name: freym-api-js
  namespace: fraym
spec:
  type: ClusterIP
  selector:
    app: freym-api-js
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
