apiVersion: apps/v1
kind: Deployment
metadata:
  name: freym-api
  namespace: fraym
  labels:
    app: freym-api
spec:
  selector:
    matchLabels:
      app: freym-api
  template:
    metadata:
      labels:
        app: freym-api
    spec:
      containers:
        - name: freym-api
          image: golang:alpine
          imagePullPolicy: Never
          command: ["sleep", "infinity"]
