apiVersion: apps/v1
kind: Deployment
metadata:
  name: freym-api-js
  namespace: fraym
  labels:
    app: freym-api-js
spec:
  selector:
    matchLabels:
      app: freym-api-js
  template:
    metadata:
      labels:
        app: freym-api-js
    spec:
      containers:
        - name: freym-api-js
          image: golang:alpine
          imagePullPolicy: Never
          command: ["sleep", "infinity"]
