version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "monthly"
    versioning-strategy: "increase"
    target-branch: "main"
    labels:
      - "needs-review"
    reviewers:
      - "jesko-plitt"
  - package-ecosystem: "gomod"
    directory: "/go"
    schedule:
      interval: "monthly"
    target-branch: "main"
    allow:
      - dependency-type: "all"
    labels:
      - "needs-review"
    reviewers:
      - "jesko-plitt"
