dev:
  freym-api-js:
    image: node:20
    imagePullPolicy: Never
    command: bash

    workdir: /code
    sync:
      - ./js:/code
      - $HOME/.ssh:/root/.ssh
    secrets:
      - $HOME/.npmrc:/root/.npmrc
