// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: sync/management/lock.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LockRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LeaseId  string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3"`
	xxx_hidden_TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Resource []string               `protobuf:"bytes,3,rep,name=resource,proto3"`
	xxx_hidden_Ttl      int32                  `protobuf:"varint,4,opt,name=ttl,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_sync_management_lock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_lock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LockRequest) GetLeaseId() string {
	if x != nil {
		return x.xxx_hidden_LeaseId
	}
	return ""
}

func (x *LockRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *LockRequest) GetResource() []string {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *LockRequest) GetTtl() int32 {
	if x != nil {
		return x.xxx_hidden_Ttl
	}
	return 0
}

func (x *LockRequest) SetLeaseId(v string) {
	x.xxx_hidden_LeaseId = v
}

func (x *LockRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *LockRequest) SetResource(v []string) {
	x.xxx_hidden_Resource = v
}

func (x *LockRequest) SetTtl(v int32) {
	x.xxx_hidden_Ttl = v
}

type LockRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LeaseId  string
	TenantId string
	Resource []string
	Ttl      int32
}

func (b0 LockRequest_builder) Build() *LockRequest {
	m0 := &LockRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LeaseId = b.LeaseId
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Resource = b.Resource
	x.xxx_hidden_Ttl = b.Ttl
	return m0
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_sync_management_lock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_lock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type LockResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 LockResponse_builder) Build() *LockResponse {
	m0 := &LockResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RLockRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LeaseId  string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3"`
	xxx_hidden_TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Resource []string               `protobuf:"bytes,3,rep,name=resource,proto3"`
	xxx_hidden_Ttl      int32                  `protobuf:"varint,4,opt,name=ttl,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RLockRequest) Reset() {
	*x = RLockRequest{}
	mi := &file_sync_management_lock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RLockRequest) ProtoMessage() {}

func (x *RLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_lock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RLockRequest) GetLeaseId() string {
	if x != nil {
		return x.xxx_hidden_LeaseId
	}
	return ""
}

func (x *RLockRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *RLockRequest) GetResource() []string {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *RLockRequest) GetTtl() int32 {
	if x != nil {
		return x.xxx_hidden_Ttl
	}
	return 0
}

func (x *RLockRequest) SetLeaseId(v string) {
	x.xxx_hidden_LeaseId = v
}

func (x *RLockRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *RLockRequest) SetResource(v []string) {
	x.xxx_hidden_Resource = v
}

func (x *RLockRequest) SetTtl(v int32) {
	x.xxx_hidden_Ttl = v
}

type RLockRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LeaseId  string
	TenantId string
	Resource []string
	Ttl      int32
}

func (b0 RLockRequest_builder) Build() *RLockRequest {
	m0 := &RLockRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LeaseId = b.LeaseId
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Resource = b.Resource
	x.xxx_hidden_Ttl = b.Ttl
	return m0
}

type RLockResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RLockResponse) Reset() {
	*x = RLockResponse{}
	mi := &file_sync_management_lock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RLockResponse) ProtoMessage() {}

func (x *RLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_lock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RLockResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RLockResponse_builder) Build() *RLockResponse {
	m0 := &RLockResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type UnlockRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LeaseId  string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3"`
	xxx_hidden_TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Resource []string               `protobuf:"bytes,3,rep,name=resource,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UnlockRequest) Reset() {
	*x = UnlockRequest{}
	mi := &file_sync_management_lock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockRequest) ProtoMessage() {}

func (x *UnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_lock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UnlockRequest) GetLeaseId() string {
	if x != nil {
		return x.xxx_hidden_LeaseId
	}
	return ""
}

func (x *UnlockRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *UnlockRequest) GetResource() []string {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *UnlockRequest) SetLeaseId(v string) {
	x.xxx_hidden_LeaseId = v
}

func (x *UnlockRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *UnlockRequest) SetResource(v []string) {
	x.xxx_hidden_Resource = v
}

type UnlockRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LeaseId  string
	TenantId string
	Resource []string
}

func (b0 UnlockRequest_builder) Build() *UnlockRequest {
	m0 := &UnlockRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LeaseId = b.LeaseId
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Resource = b.Resource
	return m0
}

type UnlockResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockResponse) Reset() {
	*x = UnlockResponse{}
	mi := &file_sync_management_lock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockResponse) ProtoMessage() {}

func (x *UnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_lock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type UnlockResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 UnlockResponse_builder) Build() *UnlockResponse {
	m0 := &UnlockResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RUnlockRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LeaseId  string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3"`
	xxx_hidden_TenantId string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Resource []string               `protobuf:"bytes,3,rep,name=resource,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RUnlockRequest) Reset() {
	*x = RUnlockRequest{}
	mi := &file_sync_management_lock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RUnlockRequest) ProtoMessage() {}

func (x *RUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_lock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RUnlockRequest) GetLeaseId() string {
	if x != nil {
		return x.xxx_hidden_LeaseId
	}
	return ""
}

func (x *RUnlockRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *RUnlockRequest) GetResource() []string {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *RUnlockRequest) SetLeaseId(v string) {
	x.xxx_hidden_LeaseId = v
}

func (x *RUnlockRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *RUnlockRequest) SetResource(v []string) {
	x.xxx_hidden_Resource = v
}

type RUnlockRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	LeaseId  string
	TenantId string
	Resource []string
}

func (b0 RUnlockRequest_builder) Build() *RUnlockRequest {
	m0 := &RUnlockRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LeaseId = b.LeaseId
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Resource = b.Resource
	return m0
}

type RUnlockResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RUnlockResponse) Reset() {
	*x = RUnlockResponse{}
	mi := &file_sync_management_lock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RUnlockResponse) ProtoMessage() {}

func (x *RUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_lock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RUnlockResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RUnlockResponse_builder) Build() *RUnlockResponse {
	m0 := &RUnlockResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_sync_management_lock_proto protoreflect.FileDescriptor

const file_sync_management_lock_proto_rawDesc = "" +
	"\n" +
	"\x1async/management/lock.proto\x12\x15freym.sync.management\"s\n" +
	"\vLockRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bresource\x18\x03 \x03(\tR\bresource\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x05R\x03ttl\"\x0e\n" +
	"\fLockResponse\"t\n" +
	"\fRLockRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bresource\x18\x03 \x03(\tR\bresource\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x05R\x03ttl\"\x0f\n" +
	"\rRLockResponse\"c\n" +
	"\rUnlockRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bresource\x18\x03 \x03(\tR\bresource\"\x10\n" +
	"\x0eUnlockResponse\"d\n" +
	"\x0eRUnlockRequest\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bresource\x18\x03 \x03(\tR\bresource\"\x11\n" +
	"\x0fRUnlockResponseb\x06proto3"

var file_sync_management_lock_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sync_management_lock_proto_goTypes = []any{
	(*LockRequest)(nil),     // 0: freym.sync.management.LockRequest
	(*LockResponse)(nil),    // 1: freym.sync.management.LockResponse
	(*RLockRequest)(nil),    // 2: freym.sync.management.RLockRequest
	(*RLockResponse)(nil),   // 3: freym.sync.management.RLockResponse
	(*UnlockRequest)(nil),   // 4: freym.sync.management.UnlockRequest
	(*UnlockResponse)(nil),  // 5: freym.sync.management.UnlockResponse
	(*RUnlockRequest)(nil),  // 6: freym.sync.management.RUnlockRequest
	(*RUnlockResponse)(nil), // 7: freym.sync.management.RUnlockResponse
}
var file_sync_management_lock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_management_lock_proto_init() }
func file_sync_management_lock_proto_init() {
	if File_sync_management_lock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_management_lock_proto_rawDesc), len(file_sync_management_lock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_management_lock_proto_goTypes,
		DependencyIndexes: file_sync_management_lock_proto_depIdxs,
		MessageInfos:      file_sync_management_lock_proto_msgTypes,
	}.Build()
	File_sync_management_lock_proto = out.File
	file_sync_management_lock_proto_goTypes = nil
	file_sync_management_lock_proto_depIdxs = nil
}
