// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: sync/management/peer_nodes.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPeerNodesRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_App string                 `protobuf:"bytes,1,opt,name=app,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPeerNodesRequest) Reset() {
	*x = GetPeerNodesRequest{}
	mi := &file_sync_management_peer_nodes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerNodesRequest) ProtoMessage() {}

func (x *GetPeerNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_peer_nodes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPeerNodesRequest) GetApp() string {
	if x != nil {
		return x.xxx_hidden_App
	}
	return ""
}

func (x *GetPeerNodesRequest) SetApp(v string) {
	x.xxx_hidden_App = v
}

type GetPeerNodesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	App string
}

func (b0 GetPeerNodesRequest_builder) Build() *GetPeerNodesRequest {
	m0 := &GetPeerNodesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_App = b.App
	return m0
}

type GetPeerNodesResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PeerNodeIp []string               `protobuf:"bytes,1,rep,name=peer_node_ip,json=peerNodeIp,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetPeerNodesResponse) Reset() {
	*x = GetPeerNodesResponse{}
	mi := &file_sync_management_peer_nodes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerNodesResponse) ProtoMessage() {}

func (x *GetPeerNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sync_management_peer_nodes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetPeerNodesResponse) GetPeerNodeIp() []string {
	if x != nil {
		return x.xxx_hidden_PeerNodeIp
	}
	return nil
}

func (x *GetPeerNodesResponse) SetPeerNodeIp(v []string) {
	x.xxx_hidden_PeerNodeIp = v
}

type GetPeerNodesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PeerNodeIp []string
}

func (b0 GetPeerNodesResponse_builder) Build() *GetPeerNodesResponse {
	m0 := &GetPeerNodesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PeerNodeIp = b.PeerNodeIp
	return m0
}

var File_sync_management_peer_nodes_proto protoreflect.FileDescriptor

var file_sync_management_peer_nodes_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x73, 0x79, 0x6e, 0x63, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x66, 0x72, 0x65, 0x79, 0x6d, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x27, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x70, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61,
	0x70, 0x70, 0x22, 0x38, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x64,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x70, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var file_sync_management_peer_nodes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sync_management_peer_nodes_proto_goTypes = []any{
	(*GetPeerNodesRequest)(nil),  // 0: freym.sync.management.GetPeerNodesRequest
	(*GetPeerNodesResponse)(nil), // 1: freym.sync.management.GetPeerNodesResponse
}
var file_sync_management_peer_nodes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sync_management_peer_nodes_proto_init() }
func file_sync_management_peer_nodes_proto_init() {
	if File_sync_management_peer_nodes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sync_management_peer_nodes_proto_rawDesc), len(file_sync_management_peer_nodes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sync_management_peer_nodes_proto_goTypes,
		DependencyIndexes: file_sync_management_peer_nodes_proto_depIdxs,
		MessageInfos:      file_sync_management_peer_nodes_proto_msgTypes,
	}.Build()
	File_sync_management_peer_nodes_proto = out.File
	file_sync_management_peer_nodes_proto_goTypes = nil
	file_sync_management_peer_nodes_proto_depIdxs = nil
}
