// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: projections/delivery/delete.proto

package deliverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Projection    string                 `protobuf:"bytes,1,opt,name=projection,proto3"`
	xxx_hidden_Auth          *AuthData              `protobuf:"bytes,2,opt,name=auth,proto3"`
	xxx_hidden_DataId        string                 `protobuf:"bytes,3,opt,name=data_id,json=dataId,proto3"`
	xxx_hidden_Filter        *DataFilter            `protobuf:"bytes,4,opt,name=filter,proto3"`
	xxx_hidden_EventMetadata *EventMetadata         `protobuf:"bytes,5,opt,name=event_metadata,json=eventMetadata,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_projections_delivery_delete_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projections_delivery_delete_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRequest) GetProjection() string {
	if x != nil {
		return x.xxx_hidden_Projection
	}
	return ""
}

func (x *DeleteRequest) GetAuth() *AuthData {
	if x != nil {
		return x.xxx_hidden_Auth
	}
	return nil
}

func (x *DeleteRequest) GetDataId() string {
	if x != nil {
		return x.xxx_hidden_DataId
	}
	return ""
}

func (x *DeleteRequest) GetFilter() *DataFilter {
	if x != nil {
		return x.xxx_hidden_Filter
	}
	return nil
}

func (x *DeleteRequest) GetEventMetadata() *EventMetadata {
	if x != nil {
		return x.xxx_hidden_EventMetadata
	}
	return nil
}

func (x *DeleteRequest) SetProjection(v string) {
	x.xxx_hidden_Projection = v
}

func (x *DeleteRequest) SetAuth(v *AuthData) {
	x.xxx_hidden_Auth = v
}

func (x *DeleteRequest) SetDataId(v string) {
	x.xxx_hidden_DataId = v
}

func (x *DeleteRequest) SetFilter(v *DataFilter) {
	x.xxx_hidden_Filter = v
}

func (x *DeleteRequest) SetEventMetadata(v *EventMetadata) {
	x.xxx_hidden_EventMetadata = v
}

func (x *DeleteRequest) HasAuth() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Auth != nil
}

func (x *DeleteRequest) HasFilter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Filter != nil
}

func (x *DeleteRequest) HasEventMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventMetadata != nil
}

func (x *DeleteRequest) ClearAuth() {
	x.xxx_hidden_Auth = nil
}

func (x *DeleteRequest) ClearFilter() {
	x.xxx_hidden_Filter = nil
}

func (x *DeleteRequest) ClearEventMetadata() {
	x.xxx_hidden_EventMetadata = nil
}

type DeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Projection    string
	Auth          *AuthData
	DataId        string
	Filter        *DataFilter
	EventMetadata *EventMetadata
}

func (b0 DeleteRequest_builder) Build() *DeleteRequest {
	m0 := &DeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Projection = b.Projection
	x.xxx_hidden_Auth = b.Auth
	x.xxx_hidden_DataId = b.DataId
	x.xxx_hidden_Filter = b.Filter
	x.xxx_hidden_EventMetadata = b.EventMetadata
	return m0
}

type DeleteResponse struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NumberOfDeletedEntries int64                  `protobuf:"varint,1,opt,name=number_of_deleted_entries,json=numberOfDeletedEntries,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_projections_delivery_delete_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projections_delivery_delete_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteResponse) GetNumberOfDeletedEntries() int64 {
	if x != nil {
		return x.xxx_hidden_NumberOfDeletedEntries
	}
	return 0
}

func (x *DeleteResponse) SetNumberOfDeletedEntries(v int64) {
	x.xxx_hidden_NumberOfDeletedEntries = v
}

type DeleteResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NumberOfDeletedEntries int64
}

func (b0 DeleteResponse_builder) Build() *DeleteResponse {
	m0 := &DeleteResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NumberOfDeletedEntries = b.NumberOfDeletedEntries
	return m0
}

var File_projections_delivery_delete_proto protoreflect.FileDescriptor

const file_projections_delivery_delete_proto_rawDesc = "" +
	"\n" +
	"!projections/delivery/delete.proto\x12\x1afreym.projections.delivery\x1a!projections/delivery/shared.proto\"\x94\x02\n" +
	"\rDeleteRequest\x12\x1e\n" +
	"\n" +
	"projection\x18\x01 \x01(\tR\n" +
	"projection\x128\n" +
	"\x04auth\x18\x02 \x01(\v2$.freym.projections.delivery.AuthDataR\x04auth\x12\x17\n" +
	"\adata_id\x18\x03 \x01(\tR\x06dataId\x12>\n" +
	"\x06filter\x18\x04 \x01(\v2&.freym.projections.delivery.DataFilterR\x06filter\x12P\n" +
	"\x0eevent_metadata\x18\x05 \x01(\v2).freym.projections.delivery.EventMetadataR\reventMetadata\"K\n" +
	"\x0eDeleteResponse\x129\n" +
	"\x19number_of_deleted_entries\x18\x01 \x01(\x03R\x16numberOfDeletedEntriesb\x06proto3"

var file_projections_delivery_delete_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_projections_delivery_delete_proto_goTypes = []any{
	(*DeleteRequest)(nil),  // 0: freym.projections.delivery.DeleteRequest
	(*DeleteResponse)(nil), // 1: freym.projections.delivery.DeleteResponse
	(*AuthData)(nil),       // 2: freym.projections.delivery.AuthData
	(*DataFilter)(nil),     // 3: freym.projections.delivery.DataFilter
	(*EventMetadata)(nil),  // 4: freym.projections.delivery.EventMetadata
}
var file_projections_delivery_delete_proto_depIdxs = []int32{
	2, // 0: freym.projections.delivery.DeleteRequest.auth:type_name -> freym.projections.delivery.AuthData
	3, // 1: freym.projections.delivery.DeleteRequest.filter:type_name -> freym.projections.delivery.DataFilter
	4, // 2: freym.projections.delivery.DeleteRequest.event_metadata:type_name -> freym.projections.delivery.EventMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_projections_delivery_delete_proto_init() }
func file_projections_delivery_delete_proto_init() {
	if File_projections_delivery_delete_proto != nil {
		return
	}
	file_projections_delivery_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projections_delivery_delete_proto_rawDesc), len(file_projections_delivery_delete_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_projections_delivery_delete_proto_goTypes,
		DependencyIndexes: file_projections_delivery_delete_proto_depIdxs,
		MessageInfos:      file_projections_delivery_delete_proto_msgTypes,
	}.Build()
	File_projections_delivery_delete_proto = out.File
	file_projections_delivery_delete_proto_goTypes = nil
	file_projections_delivery_delete_proto_depIdxs = nil
}
