// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: projections/delivery/shared.proto

package deliverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentTarget int32

const (
	DeploymentTarget_DEPLOYMENT_TARGET_BLUE  DeploymentTarget = 0
	DeploymentTarget_DEPLOYMENT_TARGET_GREEN DeploymentTarget = 1
)

// Enum value maps for DeploymentTarget.
var (
	DeploymentTarget_name = map[int32]string{
		0: "DEPLOYMENT_TARGET_BLUE",
		1: "DEPLOYMENT_TARGET_GREEN",
	}
	DeploymentTarget_value = map[string]int32{
		"DEPLOYMENT_TARGET_BLUE":  0,
		"DEPLOYMENT_TARGET_GREEN": 1,
	}
)

func (x DeploymentTarget) Enum() *DeploymentTarget {
	p := new(DeploymentTarget)
	*p = x
	return p
}

func (x DeploymentTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_projections_delivery_shared_proto_enumTypes[0].Descriptor()
}

func (DeploymentTarget) Type() protoreflect.EnumType {
	return &file_projections_delivery_shared_proto_enumTypes[0]
}

func (x DeploymentTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type AuthData struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_UserId   string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3"`
	xxx_hidden_Scopes   []string               `protobuf:"bytes,3,rep,name=scopes,proto3"`
	xxx_hidden_Data     map[string]string      `protobuf:"bytes,4,rep,name=data,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthData) Reset() {
	*x = AuthData{}
	mi := &file_projections_delivery_shared_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthData) ProtoMessage() {}

func (x *AuthData) ProtoReflect() protoreflect.Message {
	mi := &file_projections_delivery_shared_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthData) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *AuthData) GetUserId() string {
	if x != nil {
		return x.xxx_hidden_UserId
	}
	return ""
}

func (x *AuthData) GetScopes() []string {
	if x != nil {
		return x.xxx_hidden_Scopes
	}
	return nil
}

func (x *AuthData) GetData() map[string]string {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *AuthData) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *AuthData) SetUserId(v string) {
	x.xxx_hidden_UserId = v
}

func (x *AuthData) SetScopes(v []string) {
	x.xxx_hidden_Scopes = v
}

func (x *AuthData) SetData(v map[string]string) {
	x.xxx_hidden_Data = v
}

type AuthData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId string
	UserId   string
	Scopes   []string
	Data     map[string]string
}

func (b0 AuthData_builder) Build() *AuthData {
	m0 := &AuthData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_UserId = b.UserId
	x.xxx_hidden_Scopes = b.Scopes
	x.xxx_hidden_Data = b.Data
	return m0
}

type DataFilter struct {
	state             protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Fields map[string]*DataFieldFilter `protobuf:"bytes,1,rep,name=fields,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_And    *[]*DataFilter              `protobuf:"bytes,2,rep,name=and,proto3"`
	xxx_hidden_Or     *[]*DataFilter              `protobuf:"bytes,3,rep,name=or,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DataFilter) Reset() {
	*x = DataFilter{}
	mi := &file_projections_delivery_shared_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFilter) ProtoMessage() {}

func (x *DataFilter) ProtoReflect() protoreflect.Message {
	mi := &file_projections_delivery_shared_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataFilter) GetFields() map[string]*DataFieldFilter {
	if x != nil {
		return x.xxx_hidden_Fields
	}
	return nil
}

func (x *DataFilter) GetAnd() []*DataFilter {
	if x != nil {
		if x.xxx_hidden_And != nil {
			return *x.xxx_hidden_And
		}
	}
	return nil
}

func (x *DataFilter) GetOr() []*DataFilter {
	if x != nil {
		if x.xxx_hidden_Or != nil {
			return *x.xxx_hidden_Or
		}
	}
	return nil
}

func (x *DataFilter) SetFields(v map[string]*DataFieldFilter) {
	x.xxx_hidden_Fields = v
}

func (x *DataFilter) SetAnd(v []*DataFilter) {
	x.xxx_hidden_And = &v
}

func (x *DataFilter) SetOr(v []*DataFilter) {
	x.xxx_hidden_Or = &v
}

type DataFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Fields map[string]*DataFieldFilter
	And    []*DataFilter
	Or     []*DataFilter
}

func (b0 DataFilter_builder) Build() *DataFilter {
	m0 := &DataFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Fields = b.Fields
	x.xxx_hidden_And = &b.And
	x.xxx_hidden_Or = &b.Or
	return m0
}

type DataFieldFilter struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type      string                 `protobuf:"bytes,1,opt,name=type,proto3"`
	xxx_hidden_Operation string                 `protobuf:"bytes,2,opt,name=operation,proto3"`
	xxx_hidden_Value     string                 `protobuf:"bytes,3,opt,name=value,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DataFieldFilter) Reset() {
	*x = DataFieldFilter{}
	mi := &file_projections_delivery_shared_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFieldFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFieldFilter) ProtoMessage() {}

func (x *DataFieldFilter) ProtoReflect() protoreflect.Message {
	mi := &file_projections_delivery_shared_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataFieldFilter) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *DataFieldFilter) GetOperation() string {
	if x != nil {
		return x.xxx_hidden_Operation
	}
	return ""
}

func (x *DataFieldFilter) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *DataFieldFilter) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *DataFieldFilter) SetOperation(v string) {
	x.xxx_hidden_Operation = v
}

func (x *DataFieldFilter) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type DataFieldFilter_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type      string
	Operation string
	Value     string
}

func (b0 DataFieldFilter_builder) Build() *DataFieldFilter {
	m0 := &DataFieldFilter{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Operation = b.Operation
	x.xxx_hidden_Value = b.Value
	return m0
}

type EventMetadata struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CausationId   string                 `protobuf:"bytes,1,opt,name=causation_id,json=causationId,proto3"`
	xxx_hidden_CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3"`
	xxx_hidden_Target        DeploymentTarget       `protobuf:"varint,3,opt,name=target,proto3,enum=freym.projections.delivery.DeploymentTarget"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	mi := &file_projections_delivery_shared_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_projections_delivery_shared_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EventMetadata) GetCausationId() string {
	if x != nil {
		return x.xxx_hidden_CausationId
	}
	return ""
}

func (x *EventMetadata) GetCorrelationId() string {
	if x != nil {
		return x.xxx_hidden_CorrelationId
	}
	return ""
}

func (x *EventMetadata) GetTarget() DeploymentTarget {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return DeploymentTarget_DEPLOYMENT_TARGET_BLUE
}

func (x *EventMetadata) SetCausationId(v string) {
	x.xxx_hidden_CausationId = v
}

func (x *EventMetadata) SetCorrelationId(v string) {
	x.xxx_hidden_CorrelationId = v
}

func (x *EventMetadata) SetTarget(v DeploymentTarget) {
	x.xxx_hidden_Target = v
}

type EventMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CausationId   string
	CorrelationId string
	Target        DeploymentTarget
}

func (b0 EventMetadata_builder) Build() *EventMetadata {
	m0 := &EventMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CausationId = b.CausationId
	x.xxx_hidden_CorrelationId = b.CorrelationId
	x.xxx_hidden_Target = b.Target
	return m0
}

type DataOrder struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Field      string                 `protobuf:"bytes,1,opt,name=field,proto3"`
	xxx_hidden_Descending bool                   `protobuf:"varint,2,opt,name=descending,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DataOrder) Reset() {
	*x = DataOrder{}
	mi := &file_projections_delivery_shared_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataOrder) ProtoMessage() {}

func (x *DataOrder) ProtoReflect() protoreflect.Message {
	mi := &file_projections_delivery_shared_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DataOrder) GetField() string {
	if x != nil {
		return x.xxx_hidden_Field
	}
	return ""
}

func (x *DataOrder) GetDescending() bool {
	if x != nil {
		return x.xxx_hidden_Descending
	}
	return false
}

func (x *DataOrder) SetField(v string) {
	x.xxx_hidden_Field = v
}

func (x *DataOrder) SetDescending(v bool) {
	x.xxx_hidden_Descending = v
}

type DataOrder_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Field      string
	Descending bool
}

func (b0 DataOrder_builder) Build() *DataOrder {
	m0 := &DataOrder{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Field = b.Field
	x.xxx_hidden_Descending = b.Descending
	return m0
}

type Data struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_projections_delivery_shared_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_projections_delivery_shared_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Data) GetData() map[string]string {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *Data) SetData(v map[string]string) {
	x.xxx_hidden_Data = v
}

type Data_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data map[string]string
}

func (b0 Data_builder) Build() *Data {
	m0 := &Data{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Data = b.Data
	return m0
}

var File_projections_delivery_shared_proto protoreflect.FileDescriptor

const file_projections_delivery_shared_proto_rawDesc = "" +
	"\n" +
	"!projections/delivery/shared.proto\x12\x1afreym.projections.delivery\"\xd5\x01\n" +
	"\bAuthData\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12B\n" +
	"\x04data\x18\x04 \x03(\v2..freym.projections.delivery.AuthData.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x02\n" +
	"\n" +
	"DataFilter\x12J\n" +
	"\x06fields\x18\x01 \x03(\v22.freym.projections.delivery.DataFilter.FieldsEntryR\x06fields\x128\n" +
	"\x03and\x18\x02 \x03(\v2&.freym.projections.delivery.DataFilterR\x03and\x126\n" +
	"\x02or\x18\x03 \x03(\v2&.freym.projections.delivery.DataFilterR\x02or\x1af\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\x05value\x18\x02 \x01(\v2+.freym.projections.delivery.DataFieldFilterR\x05value:\x028\x01\"Y\n" +
	"\x0fDataFieldFilter\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x9f\x01\n" +
	"\rEventMetadata\x12!\n" +
	"\fcausation_id\x18\x01 \x01(\tR\vcausationId\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12D\n" +
	"\x06target\x18\x03 \x01(\x0e2,.freym.projections.delivery.DeploymentTargetR\x06target\"A\n" +
	"\tDataOrder\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1e\n" +
	"\n" +
	"descending\x18\x02 \x01(\bR\n" +
	"descending\"\x7f\n" +
	"\x04Data\x12>\n" +
	"\x04data\x18\x01 \x03(\v2*.freym.projections.delivery.Data.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*K\n" +
	"\x10DeploymentTarget\x12\x1a\n" +
	"\x16DEPLOYMENT_TARGET_BLUE\x10\x00\x12\x1b\n" +
	"\x17DEPLOYMENT_TARGET_GREEN\x10\x01b\x06proto3"

var file_projections_delivery_shared_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_projections_delivery_shared_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_projections_delivery_shared_proto_goTypes = []any{
	(DeploymentTarget)(0),   // 0: freym.projections.delivery.DeploymentTarget
	(*AuthData)(nil),        // 1: freym.projections.delivery.AuthData
	(*DataFilter)(nil),      // 2: freym.projections.delivery.DataFilter
	(*DataFieldFilter)(nil), // 3: freym.projections.delivery.DataFieldFilter
	(*EventMetadata)(nil),   // 4: freym.projections.delivery.EventMetadata
	(*DataOrder)(nil),       // 5: freym.projections.delivery.DataOrder
	(*Data)(nil),            // 6: freym.projections.delivery.Data
	nil,                     // 7: freym.projections.delivery.AuthData.DataEntry
	nil,                     // 8: freym.projections.delivery.DataFilter.FieldsEntry
	nil,                     // 9: freym.projections.delivery.Data.DataEntry
}
var file_projections_delivery_shared_proto_depIdxs = []int32{
	7, // 0: freym.projections.delivery.AuthData.data:type_name -> freym.projections.delivery.AuthData.DataEntry
	8, // 1: freym.projections.delivery.DataFilter.fields:type_name -> freym.projections.delivery.DataFilter.FieldsEntry
	2, // 2: freym.projections.delivery.DataFilter.and:type_name -> freym.projections.delivery.DataFilter
	2, // 3: freym.projections.delivery.DataFilter.or:type_name -> freym.projections.delivery.DataFilter
	0, // 4: freym.projections.delivery.EventMetadata.target:type_name -> freym.projections.delivery.DeploymentTarget
	9, // 5: freym.projections.delivery.Data.data:type_name -> freym.projections.delivery.Data.DataEntry
	3, // 6: freym.projections.delivery.DataFilter.FieldsEntry.value:type_name -> freym.projections.delivery.DataFieldFilter
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_projections_delivery_shared_proto_init() }
func file_projections_delivery_shared_proto_init() {
	if File_projections_delivery_shared_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projections_delivery_shared_proto_rawDesc), len(file_projections_delivery_shared_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_projections_delivery_shared_proto_goTypes,
		DependencyIndexes: file_projections_delivery_shared_proto_depIdxs,
		EnumInfos:         file_projections_delivery_shared_proto_enumTypes,
		MessageInfos:      file_projections_delivery_shared_proto_msgTypes,
	}.Build()
	File_projections_delivery_shared_proto = out.File
	file_projections_delivery_shared_proto_goTypes = nil
	file_projections_delivery_shared_proto_depIdxs = nil
}
