// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: auth/management/shared.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export interface RoleScope {
    clientId: string;
    scopeName: string;
}

export interface EventMetadata {
    causationId: string;
    correlationId: string;
    deploymentId: string;
    userId: string;
}

function createBaseRoleScope(): RoleScope {
    return { clientId: "", scopeName: "" };
}

export const RoleScope: MessageFns<RoleScope> = {
    encode(message: RoleScope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
        if (message.clientId !== "") {
            writer.uint32(10).string(message.clientId);
        }
        if (message.scopeName !== "") {
            writer.uint32(18).string(message.scopeName);
        }
        return writer;
    },

    decode(input: BinaryReader | Uint8Array, length?: number): RoleScope {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseRoleScope();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }

                    message.clientId = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }

                    message.scopeName = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },

    fromJSON(object: any): RoleScope {
        return {
            clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : "",
            scopeName: isSet(object.scopeName) ? globalThis.String(object.scopeName) : "",
        };
    },

    toJSON(message: RoleScope): unknown {
        const obj: any = {};
        if (message.clientId !== "") {
            obj.clientId = message.clientId;
        }
        if (message.scopeName !== "") {
            obj.scopeName = message.scopeName;
        }
        return obj;
    },

    create(base?: DeepPartial<RoleScope>): RoleScope {
        return RoleScope.fromPartial(base ?? {});
    },
    fromPartial(object: DeepPartial<RoleScope>): RoleScope {
        const message = createBaseRoleScope();
        message.clientId = object.clientId ?? "";
        message.scopeName = object.scopeName ?? "";
        return message;
    },
};

function createBaseEventMetadata(): EventMetadata {
    return { causationId: "", correlationId: "", deploymentId: "0", userId: "" };
}

export const EventMetadata: MessageFns<EventMetadata> = {
    encode(message: EventMetadata, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
        if (message.causationId !== "") {
            writer.uint32(10).string(message.causationId);
        }
        if (message.correlationId !== "") {
            writer.uint32(18).string(message.correlationId);
        }
        if (message.deploymentId !== "0") {
            writer.uint32(24).int64(message.deploymentId);
        }
        if (message.userId !== "") {
            writer.uint32(34).string(message.userId);
        }
        return writer;
    },

    decode(input: BinaryReader | Uint8Array, length?: number): EventMetadata {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseEventMetadata();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }

                    message.causationId = reader.string();
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }

                    message.correlationId = reader.string();
                    continue;
                }
                case 3: {
                    if (tag !== 24) {
                        break;
                    }

                    message.deploymentId = reader.int64().toString();
                    continue;
                }
                case 4: {
                    if (tag !== 34) {
                        break;
                    }

                    message.userId = reader.string();
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },

    fromJSON(object: any): EventMetadata {
        return {
            causationId: isSet(object.causationId) ? globalThis.String(object.causationId) : "",
            correlationId: isSet(object.correlationId)
                ? globalThis.String(object.correlationId)
                : "",
            deploymentId: isSet(object.deploymentId) ? globalThis.String(object.deploymentId) : "0",
            userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
        };
    },

    toJSON(message: EventMetadata): unknown {
        const obj: any = {};
        if (message.causationId !== "") {
            obj.causationId = message.causationId;
        }
        if (message.correlationId !== "") {
            obj.correlationId = message.correlationId;
        }
        if (message.deploymentId !== "0") {
            obj.deploymentId = message.deploymentId;
        }
        if (message.userId !== "") {
            obj.userId = message.userId;
        }
        return obj;
    },

    create(base?: DeepPartial<EventMetadata>): EventMetadata {
        return EventMetadata.fromPartial(base ?? {});
    },
    fromPartial(object: DeepPartial<EventMetadata>): EventMetadata {
        const message = createBaseEventMetadata();
        message.causationId = object.causationId ?? "";
        message.correlationId = object.correlationId ?? "";
        message.deploymentId = object.deploymentId ?? "0";
        message.userId = object.userId ?? "";
        return message;
    },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
    ? T
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends { $case: string }
          ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
          : T extends {}
            ? { [K in keyof T]?: DeepPartial<T[K]> }
            : Partial<T>;

function isSet(value: any): boolean {
    return value !== null && value !== undefined;
}

interface MessageFns<T> {
    encode(message: T, writer?: BinaryWriter): BinaryWriter;
    decode(input: BinaryReader | Uint8Array, length?: number): T;
    fromJSON(object: any): T;
    toJSON(message: T): unknown;
    create(base?: DeepPartial<T>): T;
    fromPartial(object: DeepPartial<T>): T;
}
