// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: sync/management/service.proto
import {
    type CallOptions,
    type ChannelCredentials,
    Client,
    type ClientOptions,
    type ClientReadableStream,
    type ClientUnaryCall,
    type Metadata,
    type ServiceError,
    type UntypedServiceImplementation,
    type handleServerStreamingCall,
    type handleUnaryCall,
    makeGenericClientConstructor,
} from "@grpc/grpc-js";
import {
    CreateLeaseRequest,
    CreateLeaseResponse,
    DropLeaseRequest,
    DropLeaseResponse,
    KeepLeaseRequest,
    KeepLeaseResponse,
} from "./lease";
import {
    LockRequest,
    LockResponse,
    RLockRequest,
    RLockResponse,
    RUnlockRequest,
    RUnlockResponse,
    TryLockRequest,
    TryLockResponse,
    TryRLockRequest,
    TryRLockResponse,
    UnlockRequest,
    UnlockResponse,
} from "./lock";
import { GetPeerNodesRequest, GetPeerNodesResponse } from "./peer_nodes";

export type ServiceService = typeof ServiceService;
export const ServiceService = {
    createLease: {
        path: "/freym.sync.management.Service/CreateLease",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value: CreateLeaseRequest): Buffer =>
            Buffer.from(CreateLeaseRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): CreateLeaseRequest => CreateLeaseRequest.decode(value),
        responseSerialize: (value: CreateLeaseResponse): Buffer =>
            Buffer.from(CreateLeaseResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): CreateLeaseResponse =>
            CreateLeaseResponse.decode(value),
    },
    keepLease: {
        path: "/freym.sync.management.Service/KeepLease",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value: KeepLeaseRequest): Buffer =>
            Buffer.from(KeepLeaseRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): KeepLeaseRequest => KeepLeaseRequest.decode(value),
        responseSerialize: (value: KeepLeaseResponse): Buffer =>
            Buffer.from(KeepLeaseResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): KeepLeaseResponse => KeepLeaseResponse.decode(value),
    },
    dropLease: {
        path: "/freym.sync.management.Service/DropLease",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value: DropLeaseRequest): Buffer =>
            Buffer.from(DropLeaseRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): DropLeaseRequest => DropLeaseRequest.decode(value),
        responseSerialize: (value: DropLeaseResponse): Buffer =>
            Buffer.from(DropLeaseResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): DropLeaseResponse => DropLeaseResponse.decode(value),
    },
    getPeerNodes: {
        path: "/freym.sync.management.Service/GetPeerNodes",
        requestStream: false,
        responseStream: true,
        requestSerialize: (value: GetPeerNodesRequest): Buffer =>
            Buffer.from(GetPeerNodesRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): GetPeerNodesRequest =>
            GetPeerNodesRequest.decode(value),
        responseSerialize: (value: GetPeerNodesResponse): Buffer =>
            Buffer.from(GetPeerNodesResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): GetPeerNodesResponse =>
            GetPeerNodesResponse.decode(value),
    },
    lock: {
        path: "/freym.sync.management.Service/Lock",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value: LockRequest): Buffer =>
            Buffer.from(LockRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): LockRequest => LockRequest.decode(value),
        responseSerialize: (value: LockResponse): Buffer =>
            Buffer.from(LockResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): LockResponse => LockResponse.decode(value),
    },
    tryLock: {
        path: "/freym.sync.management.Service/TryLock",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value: TryLockRequest): Buffer =>
            Buffer.from(TryLockRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): TryLockRequest => TryLockRequest.decode(value),
        responseSerialize: (value: TryLockResponse): Buffer =>
            Buffer.from(TryLockResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): TryLockResponse => TryLockResponse.decode(value),
    },
    unlock: {
        path: "/freym.sync.management.Service/Unlock",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value: UnlockRequest): Buffer =>
            Buffer.from(UnlockRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): UnlockRequest => UnlockRequest.decode(value),
        responseSerialize: (value: UnlockResponse): Buffer =>
            Buffer.from(UnlockResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): UnlockResponse => UnlockResponse.decode(value),
    },
    rLock: {
        path: "/freym.sync.management.Service/RLock",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value: RLockRequest): Buffer =>
            Buffer.from(RLockRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): RLockRequest => RLockRequest.decode(value),
        responseSerialize: (value: RLockResponse): Buffer =>
            Buffer.from(RLockResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): RLockResponse => RLockResponse.decode(value),
    },
    tryRLock: {
        path: "/freym.sync.management.Service/TryRLock",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value: TryRLockRequest): Buffer =>
            Buffer.from(TryRLockRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): TryRLockRequest => TryRLockRequest.decode(value),
        responseSerialize: (value: TryRLockResponse): Buffer =>
            Buffer.from(TryRLockResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): TryRLockResponse => TryRLockResponse.decode(value),
    },
    rUnlock: {
        path: "/freym.sync.management.Service/RUnlock",
        requestStream: false,
        responseStream: false,
        requestSerialize: (value: RUnlockRequest): Buffer =>
            Buffer.from(RUnlockRequest.encode(value).finish()),
        requestDeserialize: (value: Buffer): RUnlockRequest => RUnlockRequest.decode(value),
        responseSerialize: (value: RUnlockResponse): Buffer =>
            Buffer.from(RUnlockResponse.encode(value).finish()),
        responseDeserialize: (value: Buffer): RUnlockResponse => RUnlockResponse.decode(value),
    },
} as const;

export interface ServiceServer extends UntypedServiceImplementation {
    createLease: handleUnaryCall<CreateLeaseRequest, CreateLeaseResponse>;
    keepLease: handleUnaryCall<KeepLeaseRequest, KeepLeaseResponse>;
    dropLease: handleUnaryCall<DropLeaseRequest, DropLeaseResponse>;
    getPeerNodes: handleServerStreamingCall<GetPeerNodesRequest, GetPeerNodesResponse>;
    lock: handleUnaryCall<LockRequest, LockResponse>;
    tryLock: handleUnaryCall<TryLockRequest, TryLockResponse>;
    unlock: handleUnaryCall<UnlockRequest, UnlockResponse>;
    rLock: handleUnaryCall<RLockRequest, RLockResponse>;
    tryRLock: handleUnaryCall<TryRLockRequest, TryRLockResponse>;
    rUnlock: handleUnaryCall<RUnlockRequest, RUnlockResponse>;
}

export interface ServiceClient extends Client {
    createLease(
        request: CreateLeaseRequest,
        callback: (error: ServiceError | null, response: CreateLeaseResponse) => void
    ): ClientUnaryCall;
    createLease(
        request: CreateLeaseRequest,
        metadata: Metadata,
        callback: (error: ServiceError | null, response: CreateLeaseResponse) => void
    ): ClientUnaryCall;
    createLease(
        request: CreateLeaseRequest,
        metadata: Metadata,
        options: Partial<CallOptions>,
        callback: (error: ServiceError | null, response: CreateLeaseResponse) => void
    ): ClientUnaryCall;
    keepLease(
        request: KeepLeaseRequest,
        callback: (error: ServiceError | null, response: KeepLeaseResponse) => void
    ): ClientUnaryCall;
    keepLease(
        request: KeepLeaseRequest,
        metadata: Metadata,
        callback: (error: ServiceError | null, response: KeepLeaseResponse) => void
    ): ClientUnaryCall;
    keepLease(
        request: KeepLeaseRequest,
        metadata: Metadata,
        options: Partial<CallOptions>,
        callback: (error: ServiceError | null, response: KeepLeaseResponse) => void
    ): ClientUnaryCall;
    dropLease(
        request: DropLeaseRequest,
        callback: (error: ServiceError | null, response: DropLeaseResponse) => void
    ): ClientUnaryCall;
    dropLease(
        request: DropLeaseRequest,
        metadata: Metadata,
        callback: (error: ServiceError | null, response: DropLeaseResponse) => void
    ): ClientUnaryCall;
    dropLease(
        request: DropLeaseRequest,
        metadata: Metadata,
        options: Partial<CallOptions>,
        callback: (error: ServiceError | null, response: DropLeaseResponse) => void
    ): ClientUnaryCall;
    getPeerNodes(
        request: GetPeerNodesRequest,
        options?: Partial<CallOptions>
    ): ClientReadableStream<GetPeerNodesResponse>;
    getPeerNodes(
        request: GetPeerNodesRequest,
        metadata?: Metadata,
        options?: Partial<CallOptions>
    ): ClientReadableStream<GetPeerNodesResponse>;
    lock(
        request: LockRequest,
        callback: (error: ServiceError | null, response: LockResponse) => void
    ): ClientUnaryCall;
    lock(
        request: LockRequest,
        metadata: Metadata,
        callback: (error: ServiceError | null, response: LockResponse) => void
    ): ClientUnaryCall;
    lock(
        request: LockRequest,
        metadata: Metadata,
        options: Partial<CallOptions>,
        callback: (error: ServiceError | null, response: LockResponse) => void
    ): ClientUnaryCall;
    tryLock(
        request: TryLockRequest,
        callback: (error: ServiceError | null, response: TryLockResponse) => void
    ): ClientUnaryCall;
    tryLock(
        request: TryLockRequest,
        metadata: Metadata,
        callback: (error: ServiceError | null, response: TryLockResponse) => void
    ): ClientUnaryCall;
    tryLock(
        request: TryLockRequest,
        metadata: Metadata,
        options: Partial<CallOptions>,
        callback: (error: ServiceError | null, response: TryLockResponse) => void
    ): ClientUnaryCall;
    unlock(
        request: UnlockRequest,
        callback: (error: ServiceError | null, response: UnlockResponse) => void
    ): ClientUnaryCall;
    unlock(
        request: UnlockRequest,
        metadata: Metadata,
        callback: (error: ServiceError | null, response: UnlockResponse) => void
    ): ClientUnaryCall;
    unlock(
        request: UnlockRequest,
        metadata: Metadata,
        options: Partial<CallOptions>,
        callback: (error: ServiceError | null, response: UnlockResponse) => void
    ): ClientUnaryCall;
    rLock(
        request: RLockRequest,
        callback: (error: ServiceError | null, response: RLockResponse) => void
    ): ClientUnaryCall;
    rLock(
        request: RLockRequest,
        metadata: Metadata,
        callback: (error: ServiceError | null, response: RLockResponse) => void
    ): ClientUnaryCall;
    rLock(
        request: RLockRequest,
        metadata: Metadata,
        options: Partial<CallOptions>,
        callback: (error: ServiceError | null, response: RLockResponse) => void
    ): ClientUnaryCall;
    tryRLock(
        request: TryRLockRequest,
        callback: (error: ServiceError | null, response: TryRLockResponse) => void
    ): ClientUnaryCall;
    tryRLock(
        request: TryRLockRequest,
        metadata: Metadata,
        callback: (error: ServiceError | null, response: TryRLockResponse) => void
    ): ClientUnaryCall;
    tryRLock(
        request: TryRLockRequest,
        metadata: Metadata,
        options: Partial<CallOptions>,
        callback: (error: ServiceError | null, response: TryRLockResponse) => void
    ): ClientUnaryCall;
    rUnlock(
        request: RUnlockRequest,
        callback: (error: ServiceError | null, response: RUnlockResponse) => void
    ): ClientUnaryCall;
    rUnlock(
        request: RUnlockRequest,
        metadata: Metadata,
        callback: (error: ServiceError | null, response: RUnlockResponse) => void
    ): ClientUnaryCall;
    rUnlock(
        request: RUnlockRequest,
        metadata: Metadata,
        options: Partial<CallOptions>,
        callback: (error: ServiceError | null, response: RUnlockResponse) => void
    ): ClientUnaryCall;
}

export const ServiceClient = makeGenericClientConstructor(
    ServiceService,
    "freym.sync.management.Service"
) as unknown as {
    new (
        address: string,
        credentials: ChannelCredentials,
        options?: Partial<ClientOptions>
    ): ServiceClient;
    service: typeof ServiceService;
    serviceName: string;
};
