// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: streams/management/erroneous.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListErroneousEventsRequest struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId                string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Topic                   string                 `protobuf:"bytes,2,opt,name=topic,proto3"`
	xxx_hidden_EventTypes              []string               `protobuf:"bytes,3,rep,name=event_types,json=eventTypes,proto3"`
	xxx_hidden_Limit                   int64                  `protobuf:"varint,4,opt,name=limit,proto3"`
	xxx_hidden_ParallelTopicProcessing bool                   `protobuf:"varint,5,opt,name=parallel_topic_processing,json=parallelTopicProcessing,proto3"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *ListErroneousEventsRequest) Reset() {
	*x = ListErroneousEventsRequest{}
	mi := &file_streams_management_erroneous_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListErroneousEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListErroneousEventsRequest) ProtoMessage() {}

func (x *ListErroneousEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streams_management_erroneous_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListErroneousEventsRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *ListErroneousEventsRequest) GetTopic() string {
	if x != nil {
		return x.xxx_hidden_Topic
	}
	return ""
}

func (x *ListErroneousEventsRequest) GetEventTypes() []string {
	if x != nil {
		return x.xxx_hidden_EventTypes
	}
	return nil
}

func (x *ListErroneousEventsRequest) GetLimit() int64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListErroneousEventsRequest) GetParallelTopicProcessing() bool {
	if x != nil {
		return x.xxx_hidden_ParallelTopicProcessing
	}
	return false
}

func (x *ListErroneousEventsRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *ListErroneousEventsRequest) SetTopic(v string) {
	x.xxx_hidden_Topic = v
}

func (x *ListErroneousEventsRequest) SetEventTypes(v []string) {
	x.xxx_hidden_EventTypes = v
}

func (x *ListErroneousEventsRequest) SetLimit(v int64) {
	x.xxx_hidden_Limit = v
}

func (x *ListErroneousEventsRequest) SetParallelTopicProcessing(v bool) {
	x.xxx_hidden_ParallelTopicProcessing = v
}

type ListErroneousEventsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId                string
	Topic                   string
	EventTypes              []string
	Limit                   int64
	ParallelTopicProcessing bool
}

func (b0 ListErroneousEventsRequest_builder) Build() *ListErroneousEventsRequest {
	m0 := &ListErroneousEventsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Topic = b.Topic
	x.xxx_hidden_EventTypes = b.EventTypes
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_ParallelTopicProcessing = b.ParallelTopicProcessing
	return m0
}

type ListErroneousEventsResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Events *[]*ErroneousEvent     `protobuf:"bytes,1,rep,name=events,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListErroneousEventsResponse) Reset() {
	*x = ListErroneousEventsResponse{}
	mi := &file_streams_management_erroneous_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListErroneousEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListErroneousEventsResponse) ProtoMessage() {}

func (x *ListErroneousEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streams_management_erroneous_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListErroneousEventsResponse) GetEvents() []*ErroneousEvent {
	if x != nil {
		if x.xxx_hidden_Events != nil {
			return *x.xxx_hidden_Events
		}
	}
	return nil
}

func (x *ListErroneousEventsResponse) SetEvents(v []*ErroneousEvent) {
	x.xxx_hidden_Events = &v
}

type ListErroneousEventsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Events []*ErroneousEvent
}

func (b0 ListErroneousEventsResponse_builder) Build() *ListErroneousEventsResponse {
	m0 := &ListErroneousEventsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Events = &b.Events
	return m0
}

type ErroneousEvent struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3"`
	xxx_hidden_ConsumerGroup string                 `protobuf:"bytes,2,opt,name=consumer_group,json=consumerGroup,proto3"`
	xxx_hidden_Error         string                 `protobuf:"bytes,3,opt,name=error,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ErroneousEvent) Reset() {
	*x = ErroneousEvent{}
	mi := &file_streams_management_erroneous_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErroneousEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErroneousEvent) ProtoMessage() {}

func (x *ErroneousEvent) ProtoReflect() protoreflect.Message {
	mi := &file_streams_management_erroneous_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ErroneousEvent) GetEvent() *Event {
	if x != nil {
		return x.xxx_hidden_Event
	}
	return nil
}

func (x *ErroneousEvent) GetConsumerGroup() string {
	if x != nil {
		return x.xxx_hidden_ConsumerGroup
	}
	return ""
}

func (x *ErroneousEvent) GetError() string {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return ""
}

func (x *ErroneousEvent) SetEvent(v *Event) {
	x.xxx_hidden_Event = v
}

func (x *ErroneousEvent) SetConsumerGroup(v string) {
	x.xxx_hidden_ConsumerGroup = v
}

func (x *ErroneousEvent) SetError(v string) {
	x.xxx_hidden_Error = v
}

func (x *ErroneousEvent) HasEvent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Event != nil
}

func (x *ErroneousEvent) ClearEvent() {
	x.xxx_hidden_Event = nil
}

type ErroneousEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Event         *Event
	ConsumerGroup string
	Error         string
}

func (b0 ErroneousEvent_builder) Build() *ErroneousEvent {
	m0 := &ErroneousEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Event = b.Event
	x.xxx_hidden_ConsumerGroup = b.ConsumerGroup
	x.xxx_hidden_Error = b.Error
	return m0
}

type ResendErroneousEventRequest struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId                string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Topic                   string                 `protobuf:"bytes,2,opt,name=topic,proto3"`
	xxx_hidden_ConsumerGroup           string                 `protobuf:"bytes,3,opt,name=consumer_group,json=consumerGroup,proto3"`
	xxx_hidden_EventId                 string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3"`
	xxx_hidden_ParallelTopicProcessing bool                   `protobuf:"varint,5,opt,name=parallel_topic_processing,json=parallelTopicProcessing,proto3"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *ResendErroneousEventRequest) Reset() {
	*x = ResendErroneousEventRequest{}
	mi := &file_streams_management_erroneous_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendErroneousEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendErroneousEventRequest) ProtoMessage() {}

func (x *ResendErroneousEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streams_management_erroneous_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResendErroneousEventRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *ResendErroneousEventRequest) GetTopic() string {
	if x != nil {
		return x.xxx_hidden_Topic
	}
	return ""
}

func (x *ResendErroneousEventRequest) GetConsumerGroup() string {
	if x != nil {
		return x.xxx_hidden_ConsumerGroup
	}
	return ""
}

func (x *ResendErroneousEventRequest) GetEventId() string {
	if x != nil {
		return x.xxx_hidden_EventId
	}
	return ""
}

func (x *ResendErroneousEventRequest) GetParallelTopicProcessing() bool {
	if x != nil {
		return x.xxx_hidden_ParallelTopicProcessing
	}
	return false
}

func (x *ResendErroneousEventRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *ResendErroneousEventRequest) SetTopic(v string) {
	x.xxx_hidden_Topic = v
}

func (x *ResendErroneousEventRequest) SetConsumerGroup(v string) {
	x.xxx_hidden_ConsumerGroup = v
}

func (x *ResendErroneousEventRequest) SetEventId(v string) {
	x.xxx_hidden_EventId = v
}

func (x *ResendErroneousEventRequest) SetParallelTopicProcessing(v bool) {
	x.xxx_hidden_ParallelTopicProcessing = v
}

type ResendErroneousEventRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId                string
	Topic                   string
	ConsumerGroup           string
	EventId                 string
	ParallelTopicProcessing bool
}

func (b0 ResendErroneousEventRequest_builder) Build() *ResendErroneousEventRequest {
	m0 := &ResendErroneousEventRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Topic = b.Topic
	x.xxx_hidden_ConsumerGroup = b.ConsumerGroup
	x.xxx_hidden_EventId = b.EventId
	x.xxx_hidden_ParallelTopicProcessing = b.ParallelTopicProcessing
	return m0
}

type ResendErroneousEventResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendErroneousEventResponse) Reset() {
	*x = ResendErroneousEventResponse{}
	mi := &file_streams_management_erroneous_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendErroneousEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendErroneousEventResponse) ProtoMessage() {}

func (x *ResendErroneousEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streams_management_erroneous_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ResendErroneousEventResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ResendErroneousEventResponse_builder) Build() *ResendErroneousEventResponse {
	m0 := &ResendErroneousEventResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_streams_management_erroneous_proto protoreflect.FileDescriptor

const file_streams_management_erroneous_proto_rawDesc = "" +
	"\n" +
	"\"streams/management/erroneous.proto\x12\x18freym.streams.management\x1a\x1estreams/management/event.proto\"\xc2\x01\n" +
	"\x1aListErroneousEventsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1f\n" +
	"\vevent_types\x18\x03 \x03(\tR\n" +
	"eventTypes\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\x12:\n" +
	"\x19parallel_topic_processing\x18\x05 \x01(\bR\x17parallelTopicProcessing\"_\n" +
	"\x1bListErroneousEventsResponse\x12@\n" +
	"\x06events\x18\x01 \x03(\v2(.freym.streams.management.ErroneousEventR\x06events\"\x84\x01\n" +
	"\x0eErroneousEvent\x125\n" +
	"\x05event\x18\x01 \x01(\v2\x1f.freym.streams.management.EventR\x05event\x12%\n" +
	"\x0econsumer_group\x18\x02 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xce\x01\n" +
	"\x1bResendErroneousEventRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12%\n" +
	"\x0econsumer_group\x18\x03 \x01(\tR\rconsumerGroup\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12:\n" +
	"\x19parallel_topic_processing\x18\x05 \x01(\bR\x17parallelTopicProcessing\"\x1e\n" +
	"\x1cResendErroneousEventResponseb\x06proto3"

var file_streams_management_erroneous_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_streams_management_erroneous_proto_goTypes = []any{
	(*ListErroneousEventsRequest)(nil),   // 0: freym.streams.management.ListErroneousEventsRequest
	(*ListErroneousEventsResponse)(nil),  // 1: freym.streams.management.ListErroneousEventsResponse
	(*ErroneousEvent)(nil),               // 2: freym.streams.management.ErroneousEvent
	(*ResendErroneousEventRequest)(nil),  // 3: freym.streams.management.ResendErroneousEventRequest
	(*ResendErroneousEventResponse)(nil), // 4: freym.streams.management.ResendErroneousEventResponse
	(*Event)(nil),                        // 5: freym.streams.management.Event
}
var file_streams_management_erroneous_proto_depIdxs = []int32{
	2, // 0: freym.streams.management.ListErroneousEventsResponse.events:type_name -> freym.streams.management.ErroneousEvent
	5, // 1: freym.streams.management.ErroneousEvent.event:type_name -> freym.streams.management.Event
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streams_management_erroneous_proto_init() }
func file_streams_management_erroneous_proto_init() {
	if File_streams_management_erroneous_proto != nil {
		return
	}
	file_streams_management_event_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streams_management_erroneous_proto_rawDesc), len(file_streams_management_erroneous_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streams_management_erroneous_proto_goTypes,
		DependencyIndexes: file_streams_management_erroneous_proto_depIdxs,
		MessageInfos:      file_streams_management_erroneous_proto_msgTypes,
	}.Build()
	File_streams_management_erroneous_proto = out.File
	file_streams_management_erroneous_proto_goTypes = nil
	file_streams_management_erroneous_proto_depIdxs = nil
}
