// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: streams/management/gdpr.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntroduceGdprOnEventFieldRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId     string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Topic        string                 `protobuf:"bytes,2,opt,name=topic,proto3"`
	xxx_hidden_EventId      string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3"`
	xxx_hidden_FieldName    string                 `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3"`
	xxx_hidden_DefaultValue string                 `protobuf:"bytes,5,opt,name=default_value,json=defaultValue,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *IntroduceGdprOnEventFieldRequest) Reset() {
	*x = IntroduceGdprOnEventFieldRequest{}
	mi := &file_streams_management_gdpr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntroduceGdprOnEventFieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroduceGdprOnEventFieldRequest) ProtoMessage() {}

func (x *IntroduceGdprOnEventFieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streams_management_gdpr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IntroduceGdprOnEventFieldRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *IntroduceGdprOnEventFieldRequest) GetTopic() string {
	if x != nil {
		return x.xxx_hidden_Topic
	}
	return ""
}

func (x *IntroduceGdprOnEventFieldRequest) GetEventId() string {
	if x != nil {
		return x.xxx_hidden_EventId
	}
	return ""
}

func (x *IntroduceGdprOnEventFieldRequest) GetFieldName() string {
	if x != nil {
		return x.xxx_hidden_FieldName
	}
	return ""
}

func (x *IntroduceGdprOnEventFieldRequest) GetDefaultValue() string {
	if x != nil {
		return x.xxx_hidden_DefaultValue
	}
	return ""
}

func (x *IntroduceGdprOnEventFieldRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *IntroduceGdprOnEventFieldRequest) SetTopic(v string) {
	x.xxx_hidden_Topic = v
}

func (x *IntroduceGdprOnEventFieldRequest) SetEventId(v string) {
	x.xxx_hidden_EventId = v
}

func (x *IntroduceGdprOnEventFieldRequest) SetFieldName(v string) {
	x.xxx_hidden_FieldName = v
}

func (x *IntroduceGdprOnEventFieldRequest) SetDefaultValue(v string) {
	x.xxx_hidden_DefaultValue = v
}

type IntroduceGdprOnEventFieldRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId     string
	Topic        string
	EventId      string
	FieldName    string
	DefaultValue string
}

func (b0 IntroduceGdprOnEventFieldRequest_builder) Build() *IntroduceGdprOnEventFieldRequest {
	m0 := &IntroduceGdprOnEventFieldRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Topic = b.Topic
	x.xxx_hidden_EventId = b.EventId
	x.xxx_hidden_FieldName = b.FieldName
	x.xxx_hidden_DefaultValue = b.DefaultValue
	return m0
}

type IntroduceGdprOnEventFieldResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntroduceGdprOnEventFieldResponse) Reset() {
	*x = IntroduceGdprOnEventFieldResponse{}
	mi := &file_streams_management_gdpr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntroduceGdprOnEventFieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroduceGdprOnEventFieldResponse) ProtoMessage() {}

func (x *IntroduceGdprOnEventFieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streams_management_gdpr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type IntroduceGdprOnEventFieldResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 IntroduceGdprOnEventFieldResponse_builder) Build() *IntroduceGdprOnEventFieldResponse {
	m0 := &IntroduceGdprOnEventFieldResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type InvalidateGdprRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Topic    string                 `protobuf:"bytes,2,opt,name=topic,proto3"`
	xxx_hidden_GdprId   string                 `protobuf:"bytes,3,opt,name=gdpr_id,json=gdprId,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InvalidateGdprRequest) Reset() {
	*x = InvalidateGdprRequest{}
	mi := &file_streams_management_gdpr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateGdprRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateGdprRequest) ProtoMessage() {}

func (x *InvalidateGdprRequest) ProtoReflect() protoreflect.Message {
	mi := &file_streams_management_gdpr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InvalidateGdprRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *InvalidateGdprRequest) GetTopic() string {
	if x != nil {
		return x.xxx_hidden_Topic
	}
	return ""
}

func (x *InvalidateGdprRequest) GetGdprId() string {
	if x != nil {
		return x.xxx_hidden_GdprId
	}
	return ""
}

func (x *InvalidateGdprRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *InvalidateGdprRequest) SetTopic(v string) {
	x.xxx_hidden_Topic = v
}

func (x *InvalidateGdprRequest) SetGdprId(v string) {
	x.xxx_hidden_GdprId = v
}

type InvalidateGdprRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId string
	Topic    string
	GdprId   string
}

func (b0 InvalidateGdprRequest_builder) Build() *InvalidateGdprRequest {
	m0 := &InvalidateGdprRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Topic = b.Topic
	x.xxx_hidden_GdprId = b.GdprId
	return m0
}

type InvalidateGdprResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateGdprResponse) Reset() {
	*x = InvalidateGdprResponse{}
	mi := &file_streams_management_gdpr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateGdprResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateGdprResponse) ProtoMessage() {}

func (x *InvalidateGdprResponse) ProtoReflect() protoreflect.Message {
	mi := &file_streams_management_gdpr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type InvalidateGdprResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 InvalidateGdprResponse_builder) Build() *InvalidateGdprResponse {
	m0 := &InvalidateGdprResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_streams_management_gdpr_proto protoreflect.FileDescriptor

var file_streams_management_gdpr_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x67, 0x64, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x18, 0x66, 0x72, 0x65, 0x79, 0x6d, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xb4, 0x01, 0x0a, 0x20, 0x49, 0x6e,
	0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70, 0x72, 0x4f, 0x6e, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x23, 0x0a, 0x21, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x47, 0x64, 0x70,
	0x72, 0x4f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x63, 0x0a, 0x15, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x64, 0x70, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x64, 0x70, 0x72, 0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x49, 0x6e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x47, 0x64, 0x70, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_streams_management_gdpr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_streams_management_gdpr_proto_goTypes = []any{
	(*IntroduceGdprOnEventFieldRequest)(nil),  // 0: freym.streams.management.IntroduceGdprOnEventFieldRequest
	(*IntroduceGdprOnEventFieldResponse)(nil), // 1: freym.streams.management.IntroduceGdprOnEventFieldResponse
	(*InvalidateGdprRequest)(nil),             // 2: freym.streams.management.InvalidateGdprRequest
	(*InvalidateGdprResponse)(nil),            // 3: freym.streams.management.InvalidateGdprResponse
}
var file_streams_management_gdpr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streams_management_gdpr_proto_init() }
func file_streams_management_gdpr_proto_init() {
	if File_streams_management_gdpr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streams_management_gdpr_proto_rawDesc), len(file_streams_management_gdpr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streams_management_gdpr_proto_goTypes,
		DependencyIndexes: file_streams_management_gdpr_proto_depIdxs,
		MessageInfos:      file_streams_management_gdpr_proto_msgTypes,
	}.Build()
	File_streams_management_gdpr_proto = out.File
	file_streams_management_gdpr_proto_goTypes = nil
	file_streams_management_gdpr_proto_depIdxs = nil
}
