// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: streams/management/service.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_streams_management_service_proto protoreflect.FileDescriptor

const file_streams_management_service_proto_rawDesc = "" +
	"\n" +
	" streams/management/service.proto\x12\x18freym.streams.management\x1a streams/management/publish.proto\x1a\"streams/management/subscribe.proto\x1a\x1estreams/management/event.proto\x1a\x1dstreams/management/gdpr.proto\x1a!streams/management/paginate.proto\x1a$streams/management/backchannel.proto\x1a\x1fstreams/management/stream.proto\x1a!streams/management/snapshot.proto\x1a\x1fstreams/management/rename.proto\x1a$streams/management/transaction.proto\x1a\"streams/management/erroneous.proto2\xa5\x12\n" +
	"\aService\x12^\n" +
	"\aPublish\x12(.freym.streams.management.PublishRequest\x1a).freym.streams.management.PublishResponse\x12h\n" +
	"\tSubscribe\x12*.freym.streams.management.SubscribeRequest\x1a+.freym.streams.management.SubscribeResponse(\x010\x01\x12V\n" +
	"\bGetEvent\x12).freym.streams.management.GetEventRequest\x1a\x1f.freym.streams.management.Event\x12^\n" +
	"\fGetLastEvent\x12-.freym.streams.management.GetLastEventRequest\x1a\x1f.freym.streams.management.Event\x12l\n" +
	"\x13GetLastHandledEvent\x124.freym.streams.management.GetLastHandledEventRequest\x1a\x1f.freym.streams.management.Event\x12l\n" +
	"\x13GetLastEventByTypes\x124.freym.streams.management.GetLastEventByTypesRequest\x1a\x1f.freym.streams.management.Event\x12s\n" +
	"\x0ePaginateEvents\x12/.freym.streams.management.PaginateEventsRequest\x1a0.freym.streams.management.PaginateEventsResponse\x12\x97\x01\n" +
	"\x1aPaginateEventsAfterEventId\x12;.freym.streams.management.PaginateEventsAfterEventIdRequest\x1a<.freym.streams.management.PaginateEventsAfterEventIdResponse\x12p\n" +
	"\rIsStreamEmpty\x12..freym.streams.management.IsStreamEmptyRequest\x1a/.freym.streams.management.IsStreamEmptyResponse\x12s\n" +
	"\x0ePaginateStream\x12/.freym.streams.management.PaginateStreamRequest\x1a0.freym.streams.management.PaginateStreamResponse\x12\x97\x01\n" +
	"\x1aPaginateStreamAfterEventId\x12;.freym.streams.management.PaginateStreamAfterEventIdRequest\x1a<.freym.streams.management.PaginateStreamAfterEventIdResponse\x12\x94\x01\n" +
	"\x19IntroduceGdprOnEventField\x12:.freym.streams.management.IntroduceGdprOnEventFieldRequest\x1a;.freym.streams.management.IntroduceGdprOnEventFieldResponse\x12s\n" +
	"\x0eInvalidateGdpr\x12/.freym.streams.management.InvalidateGdprRequest\x1a0.freym.streams.management.InvalidateGdprResponse\x12\x85\x01\n" +
	"\x14CreateStreamSnapshot\x125.freym.streams.management.CreateStreamSnapshotRequest\x1a6.freym.streams.management.CreateStreamSnapshotResponse\x12v\n" +
	"\x0fRenameEventType\x120.freym.streams.management.RenameEventTypeRequest\x1a1.freym.streams.management.RenameEventTypeResponse\x12\xa6\x01\n" +
	"\x1fWaitForTransactionalConsistency\x12@.freym.streams.management.WaitForTransactionalConsistencyRequest\x1aA.freym.streams.management.WaitForTransactionalConsistencyResponse\x12\x82\x01\n" +
	"\x13ListErroneousEvents\x124.freym.streams.management.ListErroneousEventsRequest\x1a5.freym.streams.management.ListErroneousEventsResponse\x12\x85\x01\n" +
	"\x14ResendErroneousEvent\x125.freym.streams.management.ResendErroneousEventRequest\x1a6.freym.streams.management.ResendErroneousEventResponse\x12j\n" +
	"\vBackchannel\x12,.freym.streams.management.BackchannelRequest\x1a-.freym.streams.management.BackchannelResponseb\x06proto3"

var file_streams_management_service_proto_goTypes = []any{
	(*PublishRequest)(nil),                          // 0: freym.streams.management.PublishRequest
	(*SubscribeRequest)(nil),                        // 1: freym.streams.management.SubscribeRequest
	(*GetEventRequest)(nil),                         // 2: freym.streams.management.GetEventRequest
	(*GetLastEventRequest)(nil),                     // 3: freym.streams.management.GetLastEventRequest
	(*GetLastHandledEventRequest)(nil),              // 4: freym.streams.management.GetLastHandledEventRequest
	(*GetLastEventByTypesRequest)(nil),              // 5: freym.streams.management.GetLastEventByTypesRequest
	(*PaginateEventsRequest)(nil),                   // 6: freym.streams.management.PaginateEventsRequest
	(*PaginateEventsAfterEventIdRequest)(nil),       // 7: freym.streams.management.PaginateEventsAfterEventIdRequest
	(*IsStreamEmptyRequest)(nil),                    // 8: freym.streams.management.IsStreamEmptyRequest
	(*PaginateStreamRequest)(nil),                   // 9: freym.streams.management.PaginateStreamRequest
	(*PaginateStreamAfterEventIdRequest)(nil),       // 10: freym.streams.management.PaginateStreamAfterEventIdRequest
	(*IntroduceGdprOnEventFieldRequest)(nil),        // 11: freym.streams.management.IntroduceGdprOnEventFieldRequest
	(*InvalidateGdprRequest)(nil),                   // 12: freym.streams.management.InvalidateGdprRequest
	(*CreateStreamSnapshotRequest)(nil),             // 13: freym.streams.management.CreateStreamSnapshotRequest
	(*RenameEventTypeRequest)(nil),                  // 14: freym.streams.management.RenameEventTypeRequest
	(*WaitForTransactionalConsistencyRequest)(nil),  // 15: freym.streams.management.WaitForTransactionalConsistencyRequest
	(*ListErroneousEventsRequest)(nil),              // 16: freym.streams.management.ListErroneousEventsRequest
	(*ResendErroneousEventRequest)(nil),             // 17: freym.streams.management.ResendErroneousEventRequest
	(*BackchannelRequest)(nil),                      // 18: freym.streams.management.BackchannelRequest
	(*PublishResponse)(nil),                         // 19: freym.streams.management.PublishResponse
	(*SubscribeResponse)(nil),                       // 20: freym.streams.management.SubscribeResponse
	(*Event)(nil),                                   // 21: freym.streams.management.Event
	(*PaginateEventsResponse)(nil),                  // 22: freym.streams.management.PaginateEventsResponse
	(*PaginateEventsAfterEventIdResponse)(nil),      // 23: freym.streams.management.PaginateEventsAfterEventIdResponse
	(*IsStreamEmptyResponse)(nil),                   // 24: freym.streams.management.IsStreamEmptyResponse
	(*PaginateStreamResponse)(nil),                  // 25: freym.streams.management.PaginateStreamResponse
	(*PaginateStreamAfterEventIdResponse)(nil),      // 26: freym.streams.management.PaginateStreamAfterEventIdResponse
	(*IntroduceGdprOnEventFieldResponse)(nil),       // 27: freym.streams.management.IntroduceGdprOnEventFieldResponse
	(*InvalidateGdprResponse)(nil),                  // 28: freym.streams.management.InvalidateGdprResponse
	(*CreateStreamSnapshotResponse)(nil),            // 29: freym.streams.management.CreateStreamSnapshotResponse
	(*RenameEventTypeResponse)(nil),                 // 30: freym.streams.management.RenameEventTypeResponse
	(*WaitForTransactionalConsistencyResponse)(nil), // 31: freym.streams.management.WaitForTransactionalConsistencyResponse
	(*ListErroneousEventsResponse)(nil),             // 32: freym.streams.management.ListErroneousEventsResponse
	(*ResendErroneousEventResponse)(nil),            // 33: freym.streams.management.ResendErroneousEventResponse
	(*BackchannelResponse)(nil),                     // 34: freym.streams.management.BackchannelResponse
}
var file_streams_management_service_proto_depIdxs = []int32{
	0,  // 0: freym.streams.management.Service.Publish:input_type -> freym.streams.management.PublishRequest
	1,  // 1: freym.streams.management.Service.Subscribe:input_type -> freym.streams.management.SubscribeRequest
	2,  // 2: freym.streams.management.Service.GetEvent:input_type -> freym.streams.management.GetEventRequest
	3,  // 3: freym.streams.management.Service.GetLastEvent:input_type -> freym.streams.management.GetLastEventRequest
	4,  // 4: freym.streams.management.Service.GetLastHandledEvent:input_type -> freym.streams.management.GetLastHandledEventRequest
	5,  // 5: freym.streams.management.Service.GetLastEventByTypes:input_type -> freym.streams.management.GetLastEventByTypesRequest
	6,  // 6: freym.streams.management.Service.PaginateEvents:input_type -> freym.streams.management.PaginateEventsRequest
	7,  // 7: freym.streams.management.Service.PaginateEventsAfterEventId:input_type -> freym.streams.management.PaginateEventsAfterEventIdRequest
	8,  // 8: freym.streams.management.Service.IsStreamEmpty:input_type -> freym.streams.management.IsStreamEmptyRequest
	9,  // 9: freym.streams.management.Service.PaginateStream:input_type -> freym.streams.management.PaginateStreamRequest
	10, // 10: freym.streams.management.Service.PaginateStreamAfterEventId:input_type -> freym.streams.management.PaginateStreamAfterEventIdRequest
	11, // 11: freym.streams.management.Service.IntroduceGdprOnEventField:input_type -> freym.streams.management.IntroduceGdprOnEventFieldRequest
	12, // 12: freym.streams.management.Service.InvalidateGdpr:input_type -> freym.streams.management.InvalidateGdprRequest
	13, // 13: freym.streams.management.Service.CreateStreamSnapshot:input_type -> freym.streams.management.CreateStreamSnapshotRequest
	14, // 14: freym.streams.management.Service.RenameEventType:input_type -> freym.streams.management.RenameEventTypeRequest
	15, // 15: freym.streams.management.Service.WaitForTransactionalConsistency:input_type -> freym.streams.management.WaitForTransactionalConsistencyRequest
	16, // 16: freym.streams.management.Service.ListErroneousEvents:input_type -> freym.streams.management.ListErroneousEventsRequest
	17, // 17: freym.streams.management.Service.ResendErroneousEvent:input_type -> freym.streams.management.ResendErroneousEventRequest
	18, // 18: freym.streams.management.Service.Backchannel:input_type -> freym.streams.management.BackchannelRequest
	19, // 19: freym.streams.management.Service.Publish:output_type -> freym.streams.management.PublishResponse
	20, // 20: freym.streams.management.Service.Subscribe:output_type -> freym.streams.management.SubscribeResponse
	21, // 21: freym.streams.management.Service.GetEvent:output_type -> freym.streams.management.Event
	21, // 22: freym.streams.management.Service.GetLastEvent:output_type -> freym.streams.management.Event
	21, // 23: freym.streams.management.Service.GetLastHandledEvent:output_type -> freym.streams.management.Event
	21, // 24: freym.streams.management.Service.GetLastEventByTypes:output_type -> freym.streams.management.Event
	22, // 25: freym.streams.management.Service.PaginateEvents:output_type -> freym.streams.management.PaginateEventsResponse
	23, // 26: freym.streams.management.Service.PaginateEventsAfterEventId:output_type -> freym.streams.management.PaginateEventsAfterEventIdResponse
	24, // 27: freym.streams.management.Service.IsStreamEmpty:output_type -> freym.streams.management.IsStreamEmptyResponse
	25, // 28: freym.streams.management.Service.PaginateStream:output_type -> freym.streams.management.PaginateStreamResponse
	26, // 29: freym.streams.management.Service.PaginateStreamAfterEventId:output_type -> freym.streams.management.PaginateStreamAfterEventIdResponse
	27, // 30: freym.streams.management.Service.IntroduceGdprOnEventField:output_type -> freym.streams.management.IntroduceGdprOnEventFieldResponse
	28, // 31: freym.streams.management.Service.InvalidateGdpr:output_type -> freym.streams.management.InvalidateGdprResponse
	29, // 32: freym.streams.management.Service.CreateStreamSnapshot:output_type -> freym.streams.management.CreateStreamSnapshotResponse
	30, // 33: freym.streams.management.Service.RenameEventType:output_type -> freym.streams.management.RenameEventTypeResponse
	31, // 34: freym.streams.management.Service.WaitForTransactionalConsistency:output_type -> freym.streams.management.WaitForTransactionalConsistencyResponse
	32, // 35: freym.streams.management.Service.ListErroneousEvents:output_type -> freym.streams.management.ListErroneousEventsResponse
	33, // 36: freym.streams.management.Service.ResendErroneousEvent:output_type -> freym.streams.management.ResendErroneousEventResponse
	34, // 37: freym.streams.management.Service.Backchannel:output_type -> freym.streams.management.BackchannelResponse
	19, // [19:38] is the sub-list for method output_type
	0,  // [0:19] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_streams_management_service_proto_init() }
func file_streams_management_service_proto_init() {
	if File_streams_management_service_proto != nil {
		return
	}
	file_streams_management_publish_proto_init()
	file_streams_management_subscribe_proto_init()
	file_streams_management_event_proto_init()
	file_streams_management_gdpr_proto_init()
	file_streams_management_paginate_proto_init()
	file_streams_management_backchannel_proto_init()
	file_streams_management_stream_proto_init()
	file_streams_management_snapshot_proto_init()
	file_streams_management_rename_proto_init()
	file_streams_management_transaction_proto_init()
	file_streams_management_erroneous_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streams_management_service_proto_rawDesc), len(file_streams_management_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streams_management_service_proto_goTypes,
		DependencyIndexes: file_streams_management_service_proto_depIdxs,
	}.Build()
	File_streams_management_service_proto = out.File
	file_streams_management_service_proto_goTypes = nil
	file_streams_management_service_proto_depIdxs = nil
}
