// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: crud/delivery/clone.proto

package deliverypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloneRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type          string                 `protobuf:"bytes,1,opt,name=type,proto3"`
	xxx_hidden_Auth          *AuthData              `protobuf:"bytes,2,opt,name=auth,proto3"`
	xxx_hidden_Id            string                 `protobuf:"bytes,3,opt,name=id,proto3"`
	xxx_hidden_NewId         string                 `protobuf:"bytes,4,opt,name=newId,proto3"`
	xxx_hidden_Data          map[string]string      `protobuf:"bytes,5,rep,name=data,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_EventMetadata *EventMetadata         `protobuf:"bytes,6,opt,name=event_metadata,json=eventMetadata,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CloneRequest) Reset() {
	*x = CloneRequest{}
	mi := &file_crud_delivery_clone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneRequest) ProtoMessage() {}

func (x *CloneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crud_delivery_clone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CloneRequest) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *CloneRequest) GetAuth() *AuthData {
	if x != nil {
		return x.xxx_hidden_Auth
	}
	return nil
}

func (x *CloneRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *CloneRequest) GetNewId() string {
	if x != nil {
		return x.xxx_hidden_NewId
	}
	return ""
}

func (x *CloneRequest) GetData() map[string]string {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *CloneRequest) GetEventMetadata() *EventMetadata {
	if x != nil {
		return x.xxx_hidden_EventMetadata
	}
	return nil
}

func (x *CloneRequest) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *CloneRequest) SetAuth(v *AuthData) {
	x.xxx_hidden_Auth = v
}

func (x *CloneRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *CloneRequest) SetNewId(v string) {
	x.xxx_hidden_NewId = v
}

func (x *CloneRequest) SetData(v map[string]string) {
	x.xxx_hidden_Data = v
}

func (x *CloneRequest) SetEventMetadata(v *EventMetadata) {
	x.xxx_hidden_EventMetadata = v
}

func (x *CloneRequest) HasAuth() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Auth != nil
}

func (x *CloneRequest) HasEventMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventMetadata != nil
}

func (x *CloneRequest) ClearAuth() {
	x.xxx_hidden_Auth = nil
}

func (x *CloneRequest) ClearEventMetadata() {
	x.xxx_hidden_EventMetadata = nil
}

type CloneRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type          string
	Auth          *AuthData
	Id            string
	NewId         string
	Data          map[string]string
	EventMetadata *EventMetadata
}

func (b0 CloneRequest_builder) Build() *CloneRequest {
	m0 := &CloneRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Auth = b.Auth
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_NewId = b.NewId
	x.xxx_hidden_Data = b.Data
	x.xxx_hidden_EventMetadata = b.EventMetadata
	return m0
}

type CloneResponse struct {
	state                            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NewData               map[string]string      `protobuf:"bytes,1,rep,name=new_data,json=newData,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ValidationErrors      []string               `protobuf:"bytes,2,rep,name=validation_errors,json=validationErrors,proto3"`
	xxx_hidden_FieldValidationErrors map[string]string      `protobuf:"bytes,3,rep,name=field_validation_errors,json=fieldValidationErrors,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *CloneResponse) Reset() {
	*x = CloneResponse{}
	mi := &file_crud_delivery_clone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloneResponse) ProtoMessage() {}

func (x *CloneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crud_delivery_clone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CloneResponse) GetNewData() map[string]string {
	if x != nil {
		return x.xxx_hidden_NewData
	}
	return nil
}

func (x *CloneResponse) GetValidationErrors() []string {
	if x != nil {
		return x.xxx_hidden_ValidationErrors
	}
	return nil
}

func (x *CloneResponse) GetFieldValidationErrors() map[string]string {
	if x != nil {
		return x.xxx_hidden_FieldValidationErrors
	}
	return nil
}

func (x *CloneResponse) SetNewData(v map[string]string) {
	x.xxx_hidden_NewData = v
}

func (x *CloneResponse) SetValidationErrors(v []string) {
	x.xxx_hidden_ValidationErrors = v
}

func (x *CloneResponse) SetFieldValidationErrors(v map[string]string) {
	x.xxx_hidden_FieldValidationErrors = v
}

type CloneResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NewData               map[string]string
	ValidationErrors      []string
	FieldValidationErrors map[string]string
}

func (b0 CloneResponse_builder) Build() *CloneResponse {
	m0 := &CloneResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NewData = b.NewData
	x.xxx_hidden_ValidationErrors = b.ValidationErrors
	x.xxx_hidden_FieldValidationErrors = b.FieldValidationErrors
	return m0
}

var File_crud_delivery_clone_proto protoreflect.FileDescriptor

const file_crud_delivery_clone_proto_rawDesc = "" +
	"\n" +
	"\x19crud/delivery/clone.proto\x12\x13freym.crud.delivery\x1a\x1acrud/delivery/shared.proto\"\xc0\x02\n" +
	"\fCloneRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x121\n" +
	"\x04auth\x18\x02 \x01(\v2\x1d.freym.crud.delivery.AuthDataR\x04auth\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x14\n" +
	"\x05newId\x18\x04 \x01(\tR\x05newId\x12?\n" +
	"\x04data\x18\x05 \x03(\v2+.freym.crud.delivery.CloneRequest.DataEntryR\x04data\x12I\n" +
	"\x0eevent_metadata\x18\x06 \x01(\v2\".freym.crud.delivery.EventMetadataR\reventMetadata\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x03\n" +
	"\rCloneResponse\x12J\n" +
	"\bnew_data\x18\x01 \x03(\v2/.freym.crud.delivery.CloneResponse.NewDataEntryR\anewData\x12+\n" +
	"\x11validation_errors\x18\x02 \x03(\tR\x10validationErrors\x12u\n" +
	"\x17field_validation_errors\x18\x03 \x03(\v2=.freym.crud.delivery.CloneResponse.FieldValidationErrorsEntryR\x15fieldValidationErrors\x1a:\n" +
	"\fNewDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aH\n" +
	"\x1aFieldValidationErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01b\x06proto3"

var file_crud_delivery_clone_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_crud_delivery_clone_proto_goTypes = []any{
	(*CloneRequest)(nil),  // 0: freym.crud.delivery.CloneRequest
	(*CloneResponse)(nil), // 1: freym.crud.delivery.CloneResponse
	nil,                   // 2: freym.crud.delivery.CloneRequest.DataEntry
	nil,                   // 3: freym.crud.delivery.CloneResponse.NewDataEntry
	nil,                   // 4: freym.crud.delivery.CloneResponse.FieldValidationErrorsEntry
	(*AuthData)(nil),      // 5: freym.crud.delivery.AuthData
	(*EventMetadata)(nil), // 6: freym.crud.delivery.EventMetadata
}
var file_crud_delivery_clone_proto_depIdxs = []int32{
	5, // 0: freym.crud.delivery.CloneRequest.auth:type_name -> freym.crud.delivery.AuthData
	2, // 1: freym.crud.delivery.CloneRequest.data:type_name -> freym.crud.delivery.CloneRequest.DataEntry
	6, // 2: freym.crud.delivery.CloneRequest.event_metadata:type_name -> freym.crud.delivery.EventMetadata
	3, // 3: freym.crud.delivery.CloneResponse.new_data:type_name -> freym.crud.delivery.CloneResponse.NewDataEntry
	4, // 4: freym.crud.delivery.CloneResponse.field_validation_errors:type_name -> freym.crud.delivery.CloneResponse.FieldValidationErrorsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_crud_delivery_clone_proto_init() }
func file_crud_delivery_clone_proto_init() {
	if File_crud_delivery_clone_proto != nil {
		return
	}
	file_crud_delivery_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crud_delivery_clone_proto_rawDesc), len(file_crud_delivery_clone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crud_delivery_clone_proto_goTypes,
		DependencyIndexes: file_crud_delivery_clone_proto_depIdxs,
		MessageInfos:      file_crud_delivery_clone_proto_msgTypes,
	}.Build()
	File_crud_delivery_clone_proto = out.File
	file_crud_delivery_clone_proto_goTypes = nil
	file_crud_delivery_clone_proto_depIdxs = nil
}
