version: "2"
run:
  timeout: "3m"
  modules-download-mode: readonly

formatters:
  enable:
    - gofumpt
    - golines
  settings:
    gofumpt:
      module-path: github.com/fraym/freym-api/go
    golines:
      max-len: 120
