dev:
  freym-api:
    image: go-dev-container:latest
    imagePullPolicy: Never
    command: bash

    workdir: /code
    sync:
      - .:/code
      - $HOME/.ssh:/root/.ssh
    volumes:
      - /root/
      - /go/
    secrets:
      - ./.gitconfig:/root/.gitconfig
    securityContext:
      capabilities:
        add:
          - SYS_PTRACE
