// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: deployments/management/confirm.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmDeploymentRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeploymentId int64                  `protobuf:"varint,1,opt,name=deployment_id,json=deploymentId,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConfirmDeploymentRequest) Reset() {
	*x = ConfirmDeploymentRequest{}
	mi := &file_deployments_management_confirm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeploymentRequest) ProtoMessage() {}

func (x *ConfirmDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deployments_management_confirm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfirmDeploymentRequest) GetDeploymentId() int64 {
	if x != nil {
		return x.xxx_hidden_DeploymentId
	}
	return 0
}

func (x *ConfirmDeploymentRequest) SetDeploymentId(v int64) {
	x.xxx_hidden_DeploymentId = v
}

type ConfirmDeploymentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeploymentId int64
}

func (b0 ConfirmDeploymentRequest_builder) Build() *ConfirmDeploymentRequest {
	m0 := &ConfirmDeploymentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DeploymentId = b.DeploymentId
	return m0
}

type ConfirmDeploymentResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmDeploymentResponse) Reset() {
	*x = ConfirmDeploymentResponse{}
	mi := &file_deployments_management_confirm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmDeploymentResponse) ProtoMessage() {}

func (x *ConfirmDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_deployments_management_confirm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfirmDeploymentResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfirmDeploymentResponse_builder) Build() *ConfirmDeploymentResponse {
	m0 := &ConfirmDeploymentResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_deployments_management_confirm_proto protoreflect.FileDescriptor

const file_deployments_management_confirm_proto_rawDesc = "" +
	"\n" +
	"$deployments/management/confirm.proto\x12\x1cfreym.deployments.management\"?\n" +
	"\x18ConfirmDeploymentRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\x03R\fdeploymentId\"\x1b\n" +
	"\x19ConfirmDeploymentResponseb\x06proto3"

var file_deployments_management_confirm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_deployments_management_confirm_proto_goTypes = []any{
	(*ConfirmDeploymentRequest)(nil),  // 0: freym.deployments.management.ConfirmDeploymentRequest
	(*ConfirmDeploymentResponse)(nil), // 1: freym.deployments.management.ConfirmDeploymentResponse
}
var file_deployments_management_confirm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_deployments_management_confirm_proto_init() }
func file_deployments_management_confirm_proto_init() {
	if File_deployments_management_confirm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deployments_management_confirm_proto_rawDesc), len(file_deployments_management_confirm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deployments_management_confirm_proto_goTypes,
		DependencyIndexes: file_deployments_management_confirm_proto_depIdxs,
		MessageInfos:      file_deployments_management_confirm_proto_msgTypes,
	}.Build()
	File_deployments_management_confirm_proto = out.File
	file_deployments_management_confirm_proto_goTypes = nil
	file_deployments_management_confirm_proto_depIdxs = nil
}
