// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.3
// source: streams/management/backchannel.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Event } from "./event";

export interface BackchannelEventRequest {
    payload?:
        | { $case: "broadcast"; broadcast: Event }
        | { $case: "notice"; notice: Event }
        | undefined;
}

export interface BackchannelEventResponse {}

function createBaseBackchannelEventRequest(): BackchannelEventRequest {
    return { payload: undefined };
}

export const BackchannelEventRequest: MessageFns<BackchannelEventRequest> = {
    encode(
        message: BackchannelEventRequest,
        writer: BinaryWriter = new BinaryWriter()
    ): BinaryWriter {
        switch (message.payload?.$case) {
            case "broadcast":
                Event.encode(message.payload.broadcast, writer.uint32(10).fork()).join();
                break;
            case "notice":
                Event.encode(message.payload.notice, writer.uint32(18).fork()).join();
                break;
        }
        return writer;
    },

    decode(input: BinaryReader | Uint8Array, length?: number): BackchannelEventRequest {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseBackchannelEventRequest();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
                case 1: {
                    if (tag !== 10) {
                        break;
                    }

                    message.payload = {
                        $case: "broadcast",
                        broadcast: Event.decode(reader, reader.uint32()),
                    };
                    continue;
                }
                case 2: {
                    if (tag !== 18) {
                        break;
                    }

                    message.payload = {
                        $case: "notice",
                        notice: Event.decode(reader, reader.uint32()),
                    };
                    continue;
                }
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },

    fromJSON(object: any): BackchannelEventRequest {
        return {
            payload: isSet(object.broadcast)
                ? { $case: "broadcast", broadcast: Event.fromJSON(object.broadcast) }
                : isSet(object.notice)
                  ? { $case: "notice", notice: Event.fromJSON(object.notice) }
                  : undefined,
        };
    },

    toJSON(message: BackchannelEventRequest): unknown {
        const obj: any = {};
        if (message.payload?.$case === "broadcast") {
            obj.broadcast = Event.toJSON(message.payload.broadcast);
        } else if (message.payload?.$case === "notice") {
            obj.notice = Event.toJSON(message.payload.notice);
        }
        return obj;
    },

    create(base?: DeepPartial<BackchannelEventRequest>): BackchannelEventRequest {
        return BackchannelEventRequest.fromPartial(base ?? {});
    },
    fromPartial(object: DeepPartial<BackchannelEventRequest>): BackchannelEventRequest {
        const message = createBaseBackchannelEventRequest();
        switch (object.payload?.$case) {
            case "broadcast": {
                if (object.payload?.broadcast !== undefined && object.payload?.broadcast !== null) {
                    message.payload = {
                        $case: "broadcast",
                        broadcast: Event.fromPartial(object.payload.broadcast),
                    };
                }
                break;
            }
            case "notice": {
                if (object.payload?.notice !== undefined && object.payload?.notice !== null) {
                    message.payload = {
                        $case: "notice",
                        notice: Event.fromPartial(object.payload.notice),
                    };
                }
                break;
            }
        }
        return message;
    },
};

function createBaseBackchannelEventResponse(): BackchannelEventResponse {
    return {};
}

export const BackchannelEventResponse: MessageFns<BackchannelEventResponse> = {
    encode(_: BackchannelEventResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
        return writer;
    },

    decode(input: BinaryReader | Uint8Array, length?: number): BackchannelEventResponse {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        let end = length === undefined ? reader.len : reader.pos + length;
        const message = createBaseBackchannelEventResponse();
        while (reader.pos < end) {
            const tag = reader.uint32();
            switch (tag >>> 3) {
            }
            if ((tag & 7) === 4 || tag === 0) {
                break;
            }
            reader.skip(tag & 7);
        }
        return message;
    },

    fromJSON(_: any): BackchannelEventResponse {
        return {};
    },

    toJSON(_: BackchannelEventResponse): unknown {
        const obj: any = {};
        return obj;
    },

    create(base?: DeepPartial<BackchannelEventResponse>): BackchannelEventResponse {
        return BackchannelEventResponse.fromPartial(base ?? {});
    },
    fromPartial(_: DeepPartial<BackchannelEventResponse>): BackchannelEventResponse {
        const message = createBaseBackchannelEventResponse();
        return message;
    },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin
    ? T
    : T extends globalThis.Array<infer U>
      ? globalThis.Array<DeepPartial<U>>
      : T extends ReadonlyArray<infer U>
        ? ReadonlyArray<DeepPartial<U>>
        : T extends { $case: string }
          ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
          : T extends {}
            ? { [K in keyof T]?: DeepPartial<T[K]> }
            : Partial<T>;

function isSet(value: any): boolean {
    return value !== null && value !== undefined;
}

interface MessageFns<T> {
    encode(message: T, writer?: BinaryWriter): BinaryWriter;
    decode(input: BinaryReader | Uint8Array, length?: number): T;
    fromJSON(object: any): T;
    toJSON(message: T): unknown;
    create(base?: DeepPartial<T>): T;
    fromPartial(object: DeepPartial<T>): T;
}
