// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: projections/management/deployment.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploymentTarget int32

const (
	DeploymentTarget_DEPLOYMENT_TARGET_BLUE  DeploymentTarget = 0
	DeploymentTarget_DEPLOYMENT_TARGET_GREEN DeploymentTarget = 1
)

// Enum value maps for DeploymentTarget.
var (
	DeploymentTarget_name = map[int32]string{
		0: "DEPLOYMENT_TARGET_BLUE",
		1: "DEPLOYMENT_TARGET_GREEN",
	}
	DeploymentTarget_value = map[string]int32{
		"DEPLOYMENT_TARGET_BLUE":  0,
		"DEPLOYMENT_TARGET_GREEN": 1,
	}
)

func (x DeploymentTarget) Enum() *DeploymentTarget {
	p := new(DeploymentTarget)
	*p = x
	return p
}

func (x DeploymentTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeploymentTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_projections_management_deployment_proto_enumTypes[0].Descriptor()
}

func (DeploymentTarget) Type() protoreflect.EnumType {
	return &file_projections_management_deployment_proto_enumTypes[0]
}

func (x DeploymentTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type DeploySchemaRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeploymentId    int64                  `protobuf:"varint,1,opt,name=deployment_id,json=deploymentId,proto3"`
	xxx_hidden_Namespace       string                 `protobuf:"bytes,2,opt,name=namespace,proto3"`
	xxx_hidden_ProjectionTypes *[]*ObjectType         `protobuf:"bytes,3,rep,name=projection_types,json=projectionTypes,proto3"`
	xxx_hidden_CrudTypes       *[]*ObjectType         `protobuf:"bytes,4,rep,name=crud_types,json=crudTypes,proto3"`
	xxx_hidden_NestedTypes     *[]*ObjectType         `protobuf:"bytes,5,rep,name=nested_types,json=nestedTypes,proto3"`
	xxx_hidden_EnumTypes       *[]*EnumType           `protobuf:"bytes,6,rep,name=enum_types,json=enumTypes,proto3"`
	xxx_hidden_Options         *DeploymentOptions     `protobuf:"bytes,7,opt,name=options,proto3"`
	xxx_hidden_Views           *[]*View               `protobuf:"bytes,8,rep,name=views,proto3"`
	xxx_hidden_BaseViews       *[]*View               `protobuf:"bytes,9,rep,name=baseViews,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DeploySchemaRequest) Reset() {
	*x = DeploySchemaRequest{}
	mi := &file_projections_management_deployment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploySchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploySchemaRequest) ProtoMessage() {}

func (x *DeploySchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeploySchemaRequest) GetDeploymentId() int64 {
	if x != nil {
		return x.xxx_hidden_DeploymentId
	}
	return 0
}

func (x *DeploySchemaRequest) GetNamespace() string {
	if x != nil {
		return x.xxx_hidden_Namespace
	}
	return ""
}

func (x *DeploySchemaRequest) GetProjectionTypes() []*ObjectType {
	if x != nil {
		if x.xxx_hidden_ProjectionTypes != nil {
			return *x.xxx_hidden_ProjectionTypes
		}
	}
	return nil
}

func (x *DeploySchemaRequest) GetCrudTypes() []*ObjectType {
	if x != nil {
		if x.xxx_hidden_CrudTypes != nil {
			return *x.xxx_hidden_CrudTypes
		}
	}
	return nil
}

func (x *DeploySchemaRequest) GetNestedTypes() []*ObjectType {
	if x != nil {
		if x.xxx_hidden_NestedTypes != nil {
			return *x.xxx_hidden_NestedTypes
		}
	}
	return nil
}

func (x *DeploySchemaRequest) GetEnumTypes() []*EnumType {
	if x != nil {
		if x.xxx_hidden_EnumTypes != nil {
			return *x.xxx_hidden_EnumTypes
		}
	}
	return nil
}

func (x *DeploySchemaRequest) GetOptions() *DeploymentOptions {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return nil
}

func (x *DeploySchemaRequest) GetViews() []*View {
	if x != nil {
		if x.xxx_hidden_Views != nil {
			return *x.xxx_hidden_Views
		}
	}
	return nil
}

func (x *DeploySchemaRequest) GetBaseViews() []*View {
	if x != nil {
		if x.xxx_hidden_BaseViews != nil {
			return *x.xxx_hidden_BaseViews
		}
	}
	return nil
}

func (x *DeploySchemaRequest) SetDeploymentId(v int64) {
	x.xxx_hidden_DeploymentId = v
}

func (x *DeploySchemaRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = v
}

func (x *DeploySchemaRequest) SetProjectionTypes(v []*ObjectType) {
	x.xxx_hidden_ProjectionTypes = &v
}

func (x *DeploySchemaRequest) SetCrudTypes(v []*ObjectType) {
	x.xxx_hidden_CrudTypes = &v
}

func (x *DeploySchemaRequest) SetNestedTypes(v []*ObjectType) {
	x.xxx_hidden_NestedTypes = &v
}

func (x *DeploySchemaRequest) SetEnumTypes(v []*EnumType) {
	x.xxx_hidden_EnumTypes = &v
}

func (x *DeploySchemaRequest) SetOptions(v *DeploymentOptions) {
	x.xxx_hidden_Options = v
}

func (x *DeploySchemaRequest) SetViews(v []*View) {
	x.xxx_hidden_Views = &v
}

func (x *DeploySchemaRequest) SetBaseViews(v []*View) {
	x.xxx_hidden_BaseViews = &v
}

func (x *DeploySchemaRequest) HasOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Options != nil
}

func (x *DeploySchemaRequest) ClearOptions() {
	x.xxx_hidden_Options = nil
}

type DeploySchemaRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeploymentId    int64
	Namespace       string
	ProjectionTypes []*ObjectType
	CrudTypes       []*ObjectType
	NestedTypes     []*ObjectType
	EnumTypes       []*EnumType
	Options         *DeploymentOptions
	Views           []*View
	BaseViews       []*View
}

func (b0 DeploySchemaRequest_builder) Build() *DeploySchemaRequest {
	m0 := &DeploySchemaRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DeploymentId = b.DeploymentId
	x.xxx_hidden_Namespace = b.Namespace
	x.xxx_hidden_ProjectionTypes = &b.ProjectionTypes
	x.xxx_hidden_CrudTypes = &b.CrudTypes
	x.xxx_hidden_NestedTypes = &b.NestedTypes
	x.xxx_hidden_EnumTypes = &b.EnumTypes
	x.xxx_hidden_Options = b.Options
	x.xxx_hidden_Views = &b.Views
	x.xxx_hidden_BaseViews = &b.BaseViews
	return m0
}

type DeploySchemaResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploySchemaResponse) Reset() {
	*x = DeploySchemaResponse{}
	mi := &file_projections_management_deployment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploySchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploySchemaResponse) ProtoMessage() {}

func (x *DeploySchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeploySchemaResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeploySchemaResponse_builder) Build() *DeploySchemaResponse {
	m0 := &DeploySchemaResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ActivateSchemaRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeploymentId int64                  `protobuf:"varint,1,opt,name=deployment_id,json=deploymentId,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ActivateSchemaRequest) Reset() {
	*x = ActivateSchemaRequest{}
	mi := &file_projections_management_deployment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateSchemaRequest) ProtoMessage() {}

func (x *ActivateSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ActivateSchemaRequest) GetDeploymentId() int64 {
	if x != nil {
		return x.xxx_hidden_DeploymentId
	}
	return 0
}

func (x *ActivateSchemaRequest) SetDeploymentId(v int64) {
	x.xxx_hidden_DeploymentId = v
}

type ActivateSchemaRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeploymentId int64
}

func (b0 ActivateSchemaRequest_builder) Build() *ActivateSchemaRequest {
	m0 := &ActivateSchemaRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DeploymentId = b.DeploymentId
	return m0
}

type ActivateSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateSchemaResponse) Reset() {
	*x = ActivateSchemaResponse{}
	mi := &file_projections_management_deployment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateSchemaResponse) ProtoMessage() {}

func (x *ActivateSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ActivateSchemaResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ActivateSchemaResponse_builder) Build() *ActivateSchemaResponse {
	m0 := &ActivateSchemaResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConfirmSchemaRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeploymentId int64                  `protobuf:"varint,1,opt,name=deployment_id,json=deploymentId,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ConfirmSchemaRequest) Reset() {
	*x = ConfirmSchemaRequest{}
	mi := &file_projections_management_deployment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSchemaRequest) ProtoMessage() {}

func (x *ConfirmSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfirmSchemaRequest) GetDeploymentId() int64 {
	if x != nil {
		return x.xxx_hidden_DeploymentId
	}
	return 0
}

func (x *ConfirmSchemaRequest) SetDeploymentId(v int64) {
	x.xxx_hidden_DeploymentId = v
}

type ConfirmSchemaRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeploymentId int64
}

func (b0 ConfirmSchemaRequest_builder) Build() *ConfirmSchemaRequest {
	m0 := &ConfirmSchemaRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DeploymentId = b.DeploymentId
	return m0
}

type ConfirmSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmSchemaResponse) Reset() {
	*x = ConfirmSchemaResponse{}
	mi := &file_projections_management_deployment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmSchemaResponse) ProtoMessage() {}

func (x *ConfirmSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfirmSchemaResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfirmSchemaResponse_builder) Build() *ConfirmSchemaResponse {
	m0 := &ConfirmSchemaResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type RollbackSchemaRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Target    DeploymentTarget       `protobuf:"varint,1,opt,name=target,proto3,enum=freym.projections.management.DeploymentTarget"`
	xxx_hidden_Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RollbackSchemaRequest) Reset() {
	*x = RollbackSchemaRequest{}
	mi := &file_projections_management_deployment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackSchemaRequest) ProtoMessage() {}

func (x *RollbackSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RollbackSchemaRequest) GetTarget() DeploymentTarget {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return DeploymentTarget_DEPLOYMENT_TARGET_BLUE
}

func (x *RollbackSchemaRequest) GetNamespace() string {
	if x != nil {
		return x.xxx_hidden_Namespace
	}
	return ""
}

func (x *RollbackSchemaRequest) SetTarget(v DeploymentTarget) {
	x.xxx_hidden_Target = v
}

func (x *RollbackSchemaRequest) SetNamespace(v string) {
	x.xxx_hidden_Namespace = v
}

type RollbackSchemaRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Target    DeploymentTarget
	Namespace string
}

func (b0 RollbackSchemaRequest_builder) Build() *RollbackSchemaRequest {
	m0 := &RollbackSchemaRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Namespace = b.Namespace
	return m0
}

type RollbackSchemaByDeploymentRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeploymentId int64                  `protobuf:"varint,1,opt,name=deployment_id,json=deploymentId,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RollbackSchemaByDeploymentRequest) Reset() {
	*x = RollbackSchemaByDeploymentRequest{}
	mi := &file_projections_management_deployment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackSchemaByDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackSchemaByDeploymentRequest) ProtoMessage() {}

func (x *RollbackSchemaByDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RollbackSchemaByDeploymentRequest) GetDeploymentId() int64 {
	if x != nil {
		return x.xxx_hidden_DeploymentId
	}
	return 0
}

func (x *RollbackSchemaByDeploymentRequest) SetDeploymentId(v int64) {
	x.xxx_hidden_DeploymentId = v
}

type RollbackSchemaByDeploymentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeploymentId int64
}

func (b0 RollbackSchemaByDeploymentRequest_builder) Build() *RollbackSchemaByDeploymentRequest {
	m0 := &RollbackSchemaByDeploymentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DeploymentId = b.DeploymentId
	return m0
}

type RollbackSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackSchemaResponse) Reset() {
	*x = RollbackSchemaResponse{}
	mi := &file_projections_management_deployment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackSchemaResponse) ProtoMessage() {}

func (x *RollbackSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RollbackSchemaResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RollbackSchemaResponse_builder) Build() *RollbackSchemaResponse {
	m0 := &RollbackSchemaResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetSchemaDeploymentRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DeploymentId int64                  `protobuf:"varint,1,opt,name=deployment_id,json=deploymentId,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetSchemaDeploymentRequest) Reset() {
	*x = GetSchemaDeploymentRequest{}
	mi := &file_projections_management_deployment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaDeploymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaDeploymentRequest) ProtoMessage() {}

func (x *GetSchemaDeploymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSchemaDeploymentRequest) GetDeploymentId() int64 {
	if x != nil {
		return x.xxx_hidden_DeploymentId
	}
	return 0
}

func (x *GetSchemaDeploymentRequest) SetDeploymentId(v int64) {
	x.xxx_hidden_DeploymentId = v
}

type GetSchemaDeploymentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DeploymentId int64
}

func (b0 GetSchemaDeploymentRequest_builder) Build() *GetSchemaDeploymentRequest {
	m0 := &GetSchemaDeploymentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DeploymentId = b.DeploymentId
	return m0
}

type GetSchemaDeploymentResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Progress uint32                 `protobuf:"varint,1,opt,name=progress,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSchemaDeploymentResponse) Reset() {
	*x = GetSchemaDeploymentResponse{}
	mi := &file_projections_management_deployment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaDeploymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaDeploymentResponse) ProtoMessage() {}

func (x *GetSchemaDeploymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSchemaDeploymentResponse) GetProgress() uint32 {
	if x != nil {
		return x.xxx_hidden_Progress
	}
	return 0
}

func (x *GetSchemaDeploymentResponse) SetProgress(v uint32) {
	x.xxx_hidden_Progress = v
}

type GetSchemaDeploymentResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Progress uint32
}

func (b0 GetSchemaDeploymentResponse_builder) Build() *GetSchemaDeploymentResponse {
	m0 := &GetSchemaDeploymentResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Progress = b.Progress
	return m0
}

type DeploymentOptions struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Target     DeploymentTarget       `protobuf:"varint,1,opt,name=target,proto3,enum=freym.projections.management.DeploymentTarget"`
	xxx_hidden_Force      bool                   `protobuf:"varint,2,opt,name=force,proto3"`
	xxx_hidden_ForceTypes []string               `protobuf:"bytes,3,rep,name=force_types,json=forceTypes,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeploymentOptions) Reset() {
	*x = DeploymentOptions{}
	mi := &file_projections_management_deployment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentOptions) ProtoMessage() {}

func (x *DeploymentOptions) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeploymentOptions) GetTarget() DeploymentTarget {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return DeploymentTarget_DEPLOYMENT_TARGET_BLUE
}

func (x *DeploymentOptions) GetForce() bool {
	if x != nil {
		return x.xxx_hidden_Force
	}
	return false
}

func (x *DeploymentOptions) GetForceTypes() []string {
	if x != nil {
		return x.xxx_hidden_ForceTypes
	}
	return nil
}

func (x *DeploymentOptions) SetTarget(v DeploymentTarget) {
	x.xxx_hidden_Target = v
}

func (x *DeploymentOptions) SetForce(v bool) {
	x.xxx_hidden_Force = v
}

func (x *DeploymentOptions) SetForceTypes(v []string) {
	x.xxx_hidden_ForceTypes = v
}

type DeploymentOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Target     DeploymentTarget
	Force      bool
	ForceTypes []string
}

func (b0 DeploymentOptions_builder) Build() *DeploymentOptions {
	m0 := &DeploymentOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Force = b.Force
	x.xxx_hidden_ForceTypes = b.ForceTypes
	return m0
}

type ObjectType struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name       string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Directives *[]*TypeDirective      `protobuf:"bytes,2,rep,name=directives,proto3"`
	xxx_hidden_Fields     *[]*TypeField          `protobuf:"bytes,3,rep,name=fields,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ObjectType) Reset() {
	*x = ObjectType{}
	mi := &file_projections_management_deployment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectType) ProtoMessage() {}

func (x *ObjectType) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ObjectType) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *ObjectType) GetDirectives() []*TypeDirective {
	if x != nil {
		if x.xxx_hidden_Directives != nil {
			return *x.xxx_hidden_Directives
		}
	}
	return nil
}

func (x *ObjectType) GetFields() []*TypeField {
	if x != nil {
		if x.xxx_hidden_Fields != nil {
			return *x.xxx_hidden_Fields
		}
	}
	return nil
}

func (x *ObjectType) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *ObjectType) SetDirectives(v []*TypeDirective) {
	x.xxx_hidden_Directives = &v
}

func (x *ObjectType) SetFields(v []*TypeField) {
	x.xxx_hidden_Fields = &v
}

type ObjectType_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name       string
	Directives []*TypeDirective
	Fields     []*TypeField
}

func (b0 ObjectType_builder) Build() *ObjectType {
	m0 := &ObjectType{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Directives = &b.Directives
	x.xxx_hidden_Fields = &b.Fields
	return m0
}

type TypeDirective struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name      string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Arguments *[]*TypeArgument       `protobuf:"bytes,2,rep,name=arguments,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TypeDirective) Reset() {
	*x = TypeDirective{}
	mi := &file_projections_management_deployment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeDirective) ProtoMessage() {}

func (x *TypeDirective) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TypeDirective) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *TypeDirective) GetArguments() []*TypeArgument {
	if x != nil {
		if x.xxx_hidden_Arguments != nil {
			return *x.xxx_hidden_Arguments
		}
	}
	return nil
}

func (x *TypeDirective) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *TypeDirective) SetArguments(v []*TypeArgument) {
	x.xxx_hidden_Arguments = &v
}

type TypeDirective_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name      string
	Arguments []*TypeArgument
}

func (b0 TypeDirective_builder) Build() *TypeDirective {
	m0 := &TypeDirective{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Arguments = &b.Arguments
	return m0
}

type TypeField struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name       string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Type       []string               `protobuf:"bytes,2,rep,name=type,proto3"`
	xxx_hidden_Directives *[]*TypeDirective      `protobuf:"bytes,3,rep,name=directives,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TypeField) Reset() {
	*x = TypeField{}
	mi := &file_projections_management_deployment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeField) ProtoMessage() {}

func (x *TypeField) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TypeField) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *TypeField) GetType() []string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return nil
}

func (x *TypeField) GetDirectives() []*TypeDirective {
	if x != nil {
		if x.xxx_hidden_Directives != nil {
			return *x.xxx_hidden_Directives
		}
	}
	return nil
}

func (x *TypeField) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *TypeField) SetType(v []string) {
	x.xxx_hidden_Type = v
}

func (x *TypeField) SetDirectives(v []*TypeDirective) {
	x.xxx_hidden_Directives = &v
}

type TypeField_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name       string
	Type       []string
	Directives []*TypeDirective
}

func (b0 TypeField_builder) Build() *TypeField {
	m0 := &TypeField{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Directives = &b.Directives
	return m0
}

type TypeArgument struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name  string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TypeArgument) Reset() {
	*x = TypeArgument{}
	mi := &file_projections_management_deployment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeArgument) ProtoMessage() {}

func (x *TypeArgument) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TypeArgument) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *TypeArgument) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *TypeArgument) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *TypeArgument) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type TypeArgument_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name  string
	Value string
}

func (b0 TypeArgument_builder) Build() *TypeArgument {
	m0 := &TypeArgument{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Value = b.Value
	return m0
}

type EnumType struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name   string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Values []string               `protobuf:"bytes,2,rep,name=values,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EnumType) Reset() {
	*x = EnumType{}
	mi := &file_projections_management_deployment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumType) ProtoMessage() {}

func (x *EnumType) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnumType) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *EnumType) GetValues() []string {
	if x != nil {
		return x.xxx_hidden_Values
	}
	return nil
}

func (x *EnumType) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *EnumType) SetValues(v []string) {
	x.xxx_hidden_Values = v
}

type EnumType_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name   string
	Values []string
}

func (b0 EnumType_builder) Build() *EnumType {
	m0 := &EnumType{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Values = b.Values
	return m0
}

type View struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name       string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Sql        string                 `protobuf:"bytes,2,opt,name=sql,proto3"`
	xxx_hidden_Directives *[]*TypeDirective      `protobuf:"bytes,3,rep,name=directives,proto3"`
	xxx_hidden_Fields     *[]*TypeField          `protobuf:"bytes,4,rep,name=fields,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_projections_management_deployment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_projections_management_deployment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *View) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *View) GetSql() string {
	if x != nil {
		return x.xxx_hidden_Sql
	}
	return ""
}

func (x *View) GetDirectives() []*TypeDirective {
	if x != nil {
		if x.xxx_hidden_Directives != nil {
			return *x.xxx_hidden_Directives
		}
	}
	return nil
}

func (x *View) GetFields() []*TypeField {
	if x != nil {
		if x.xxx_hidden_Fields != nil {
			return *x.xxx_hidden_Fields
		}
	}
	return nil
}

func (x *View) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *View) SetSql(v string) {
	x.xxx_hidden_Sql = v
}

func (x *View) SetDirectives(v []*TypeDirective) {
	x.xxx_hidden_Directives = &v
}

func (x *View) SetFields(v []*TypeField) {
	x.xxx_hidden_Fields = &v
}

type View_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name       string
	Sql        string
	Directives []*TypeDirective
	Fields     []*TypeField
}

func (b0 View_builder) Build() *View {
	m0 := &View{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Sql = b.Sql
	x.xxx_hidden_Directives = &b.Directives
	x.xxx_hidden_Fields = &b.Fields
	return m0
}

var File_projections_management_deployment_proto protoreflect.FileDescriptor

const file_projections_management_deployment_proto_rawDesc = "" +
	"\n" +
	"'projections/management/deployment.proto\x12\x1cfreym.projections.management\"\xd1\x04\n" +
	"\x13DeploySchemaRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\x03R\fdeploymentId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12S\n" +
	"\x10projection_types\x18\x03 \x03(\v2(.freym.projections.management.ObjectTypeR\x0fprojectionTypes\x12G\n" +
	"\n" +
	"crud_types\x18\x04 \x03(\v2(.freym.projections.management.ObjectTypeR\tcrudTypes\x12K\n" +
	"\fnested_types\x18\x05 \x03(\v2(.freym.projections.management.ObjectTypeR\vnestedTypes\x12E\n" +
	"\n" +
	"enum_types\x18\x06 \x03(\v2&.freym.projections.management.EnumTypeR\tenumTypes\x12I\n" +
	"\aoptions\x18\a \x01(\v2/.freym.projections.management.DeploymentOptionsR\aoptions\x128\n" +
	"\x05views\x18\b \x03(\v2\".freym.projections.management.ViewR\x05views\x12@\n" +
	"\tbaseViews\x18\t \x03(\v2\".freym.projections.management.ViewR\tbaseViews\"\x16\n" +
	"\x14DeploySchemaResponse\"<\n" +
	"\x15ActivateSchemaRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\x03R\fdeploymentId\"\x18\n" +
	"\x16ActivateSchemaResponse\";\n" +
	"\x14ConfirmSchemaRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\x03R\fdeploymentId\"\x17\n" +
	"\x15ConfirmSchemaResponse\"}\n" +
	"\x15RollbackSchemaRequest\x12F\n" +
	"\x06target\x18\x01 \x01(\x0e2..freym.projections.management.DeploymentTargetR\x06target\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"H\n" +
	"!RollbackSchemaByDeploymentRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\x03R\fdeploymentId\"\x18\n" +
	"\x16RollbackSchemaResponse\"A\n" +
	"\x1aGetSchemaDeploymentRequest\x12#\n" +
	"\rdeployment_id\x18\x01 \x01(\x03R\fdeploymentId\"9\n" +
	"\x1bGetSchemaDeploymentResponse\x12\x1a\n" +
	"\bprogress\x18\x01 \x01(\rR\bprogress\"\x92\x01\n" +
	"\x11DeploymentOptions\x12F\n" +
	"\x06target\x18\x01 \x01(\x0e2..freym.projections.management.DeploymentTargetR\x06target\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\x12\x1f\n" +
	"\vforce_types\x18\x03 \x03(\tR\n" +
	"forceTypes\"\xae\x01\n" +
	"\n" +
	"ObjectType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12K\n" +
	"\n" +
	"directives\x18\x02 \x03(\v2+.freym.projections.management.TypeDirectiveR\n" +
	"directives\x12?\n" +
	"\x06fields\x18\x03 \x03(\v2'.freym.projections.management.TypeFieldR\x06fields\"m\n" +
	"\rTypeDirective\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12H\n" +
	"\targuments\x18\x02 \x03(\v2*.freym.projections.management.TypeArgumentR\targuments\"\x80\x01\n" +
	"\tTypeField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x03(\tR\x04type\x12K\n" +
	"\n" +
	"directives\x18\x03 \x03(\v2+.freym.projections.management.TypeDirectiveR\n" +
	"directives\"8\n" +
	"\fTypeArgument\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"6\n" +
	"\bEnumType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\xba\x01\n" +
	"\x04View\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12K\n" +
	"\n" +
	"directives\x18\x03 \x03(\v2+.freym.projections.management.TypeDirectiveR\n" +
	"directives\x12?\n" +
	"\x06fields\x18\x04 \x03(\v2'.freym.projections.management.TypeFieldR\x06fields*K\n" +
	"\x10DeploymentTarget\x12\x1a\n" +
	"\x16DEPLOYMENT_TARGET_BLUE\x10\x00\x12\x1b\n" +
	"\x17DEPLOYMENT_TARGET_GREEN\x10\x01b\x06proto3"

var file_projections_management_deployment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_projections_management_deployment_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_projections_management_deployment_proto_goTypes = []any{
	(DeploymentTarget)(0),                     // 0: freym.projections.management.DeploymentTarget
	(*DeploySchemaRequest)(nil),               // 1: freym.projections.management.DeploySchemaRequest
	(*DeploySchemaResponse)(nil),              // 2: freym.projections.management.DeploySchemaResponse
	(*ActivateSchemaRequest)(nil),             // 3: freym.projections.management.ActivateSchemaRequest
	(*ActivateSchemaResponse)(nil),            // 4: freym.projections.management.ActivateSchemaResponse
	(*ConfirmSchemaRequest)(nil),              // 5: freym.projections.management.ConfirmSchemaRequest
	(*ConfirmSchemaResponse)(nil),             // 6: freym.projections.management.ConfirmSchemaResponse
	(*RollbackSchemaRequest)(nil),             // 7: freym.projections.management.RollbackSchemaRequest
	(*RollbackSchemaByDeploymentRequest)(nil), // 8: freym.projections.management.RollbackSchemaByDeploymentRequest
	(*RollbackSchemaResponse)(nil),            // 9: freym.projections.management.RollbackSchemaResponse
	(*GetSchemaDeploymentRequest)(nil),        // 10: freym.projections.management.GetSchemaDeploymentRequest
	(*GetSchemaDeploymentResponse)(nil),       // 11: freym.projections.management.GetSchemaDeploymentResponse
	(*DeploymentOptions)(nil),                 // 12: freym.projections.management.DeploymentOptions
	(*ObjectType)(nil),                        // 13: freym.projections.management.ObjectType
	(*TypeDirective)(nil),                     // 14: freym.projections.management.TypeDirective
	(*TypeField)(nil),                         // 15: freym.projections.management.TypeField
	(*TypeArgument)(nil),                      // 16: freym.projections.management.TypeArgument
	(*EnumType)(nil),                          // 17: freym.projections.management.EnumType
	(*View)(nil),                              // 18: freym.projections.management.View
}
var file_projections_management_deployment_proto_depIdxs = []int32{
	13, // 0: freym.projections.management.DeploySchemaRequest.projection_types:type_name -> freym.projections.management.ObjectType
	13, // 1: freym.projections.management.DeploySchemaRequest.crud_types:type_name -> freym.projections.management.ObjectType
	13, // 2: freym.projections.management.DeploySchemaRequest.nested_types:type_name -> freym.projections.management.ObjectType
	17, // 3: freym.projections.management.DeploySchemaRequest.enum_types:type_name -> freym.projections.management.EnumType
	12, // 4: freym.projections.management.DeploySchemaRequest.options:type_name -> freym.projections.management.DeploymentOptions
	18, // 5: freym.projections.management.DeploySchemaRequest.views:type_name -> freym.projections.management.View
	18, // 6: freym.projections.management.DeploySchemaRequest.baseViews:type_name -> freym.projections.management.View
	0,  // 7: freym.projections.management.RollbackSchemaRequest.target:type_name -> freym.projections.management.DeploymentTarget
	0,  // 8: freym.projections.management.DeploymentOptions.target:type_name -> freym.projections.management.DeploymentTarget
	14, // 9: freym.projections.management.ObjectType.directives:type_name -> freym.projections.management.TypeDirective
	15, // 10: freym.projections.management.ObjectType.fields:type_name -> freym.projections.management.TypeField
	16, // 11: freym.projections.management.TypeDirective.arguments:type_name -> freym.projections.management.TypeArgument
	14, // 12: freym.projections.management.TypeField.directives:type_name -> freym.projections.management.TypeDirective
	14, // 13: freym.projections.management.View.directives:type_name -> freym.projections.management.TypeDirective
	15, // 14: freym.projections.management.View.fields:type_name -> freym.projections.management.TypeField
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_projections_management_deployment_proto_init() }
func file_projections_management_deployment_proto_init() {
	if File_projections_management_deployment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_projections_management_deployment_proto_rawDesc), len(file_projections_management_deployment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_projections_management_deployment_proto_goTypes,
		DependencyIndexes: file_projections_management_deployment_proto_depIdxs,
		EnumInfos:         file_projections_management_deployment_proto_enumTypes,
		MessageInfos:      file_projections_management_deployment_proto_msgTypes,
	}.Build()
	File_projections_management_deployment_proto = out.File
	file_projections_management_deployment_proto_goTypes = nil
	file_projections_management_deployment_proto_depIdxs = nil
}
