// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: auth/management/role_upsert.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertRoleRequest struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Id            string                 `protobuf:"bytes,2,opt,name=id,proto3"`
	xxx_hidden_AllowedScopes *[]*RoleScope          `protobuf:"bytes,3,rep,name=allowed_scopes,json=allowedScopes,proto3"`
	xxx_hidden_EventMetadata *EventMetadata         `protobuf:"bytes,4,opt,name=event_metadata,json=eventMetadata,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpsertRoleRequest) Reset() {
	*x = UpsertRoleRequest{}
	mi := &file_auth_management_role_upsert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRoleRequest) ProtoMessage() {}

func (x *UpsertRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_management_role_upsert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpsertRoleRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *UpsertRoleRequest) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *UpsertRoleRequest) GetAllowedScopes() []*RoleScope {
	if x != nil {
		if x.xxx_hidden_AllowedScopes != nil {
			return *x.xxx_hidden_AllowedScopes
		}
	}
	return nil
}

func (x *UpsertRoleRequest) GetEventMetadata() *EventMetadata {
	if x != nil {
		return x.xxx_hidden_EventMetadata
	}
	return nil
}

func (x *UpsertRoleRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *UpsertRoleRequest) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *UpsertRoleRequest) SetAllowedScopes(v []*RoleScope) {
	x.xxx_hidden_AllowedScopes = &v
}

func (x *UpsertRoleRequest) SetEventMetadata(v *EventMetadata) {
	x.xxx_hidden_EventMetadata = v
}

func (x *UpsertRoleRequest) HasEventMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EventMetadata != nil
}

func (x *UpsertRoleRequest) ClearEventMetadata() {
	x.xxx_hidden_EventMetadata = nil
}

type UpsertRoleRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId      string
	Id            string
	AllowedScopes []*RoleScope
	EventMetadata *EventMetadata
}

func (b0 UpsertRoleRequest_builder) Build() *UpsertRoleRequest {
	m0 := &UpsertRoleRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_AllowedScopes = &b.AllowedScopes
	x.xxx_hidden_EventMetadata = b.EventMetadata
	return m0
}

type UpsertRoleResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRoleResponse) Reset() {
	*x = UpsertRoleResponse{}
	mi := &file_auth_management_role_upsert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRoleResponse) ProtoMessage() {}

func (x *UpsertRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_management_role_upsert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpsertRoleResponse) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *UpsertRoleResponse) SetId(v string) {
	x.xxx_hidden_Id = v
}

type UpsertRoleResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 UpsertRoleResponse_builder) Build() *UpsertRoleResponse {
	m0 := &UpsertRoleResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

var File_auth_management_role_upsert_proto protoreflect.FileDescriptor

var file_auth_management_role_upsert_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x66, 0x72, 0x65, 0x79, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1c, 0x61, 0x75, 0x74, 0x68,
	0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x73,
	0x65, 0x72, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x47, 0x0a, 0x0e, 0x61,
	0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x72, 0x65, 0x79, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x53, 0x63,
	0x6f, 0x70, 0x65, 0x73, 0x12, 0x4b, 0x0a, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66,
	0x72, 0x65, 0x79, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x0d, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x24, 0x0a, 0x12, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_auth_management_role_upsert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_management_role_upsert_proto_goTypes = []any{
	(*UpsertRoleRequest)(nil),  // 0: freym.auth.management.UpsertRoleRequest
	(*UpsertRoleResponse)(nil), // 1: freym.auth.management.UpsertRoleResponse
	(*RoleScope)(nil),          // 2: freym.auth.management.RoleScope
	(*EventMetadata)(nil),      // 3: freym.auth.management.EventMetadata
}
var file_auth_management_role_upsert_proto_depIdxs = []int32{
	2, // 0: freym.auth.management.UpsertRoleRequest.allowed_scopes:type_name -> freym.auth.management.RoleScope
	3, // 1: freym.auth.management.UpsertRoleRequest.event_metadata:type_name -> freym.auth.management.EventMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_management_role_upsert_proto_init() }
func file_auth_management_role_upsert_proto_init() {
	if File_auth_management_role_upsert_proto != nil {
		return
	}
	file_auth_management_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_management_role_upsert_proto_rawDesc), len(file_auth_management_role_upsert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_management_role_upsert_proto_goTypes,
		DependencyIndexes: file_auth_management_role_upsert_proto_depIdxs,
		MessageInfos:      file_auth_management_role_upsert_proto_msgTypes,
	}.Build()
	File_auth_management_role_upsert_proto = out.File
	file_auth_management_role_upsert_proto_goTypes = nil
	file_auth_management_role_upsert_proto_depIdxs = nil
}
