// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: auth/management/user_create.proto

package managementpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3"`
	xxx_hidden_Login           string                 `protobuf:"bytes,2,opt,name=login,proto3"`
	xxx_hidden_Email           string                 `protobuf:"bytes,3,opt,name=email,proto3"`
	xxx_hidden_DisplayName     string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3"`
	xxx_hidden_Password        string                 `protobuf:"bytes,5,opt,name=password,proto3"`
	xxx_hidden_AssignedRoleIds []string               `protobuf:"bytes,6,rep,name=assigned_role_ids,json=assignedRoleIds,proto3"`
	xxx_hidden_Active          bool                   `protobuf:"varint,7,opt,name=active,proto3"`
	xxx_hidden_BlockedUntil    int64                  `protobuf:"varint,8,opt,name=blocked_until,json=blockedUntil,proto3"`
	xxx_hidden_Metadata        *Metadata              `protobuf:"bytes,9,opt,name=metadata,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_auth_management_user_create_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_management_user_create_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateUserRequest) GetTenantId() string {
	if x != nil {
		return x.xxx_hidden_TenantId
	}
	return ""
}

func (x *CreateUserRequest) GetLogin() string {
	if x != nil {
		return x.xxx_hidden_Login
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.xxx_hidden_Email
	}
	return ""
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.xxx_hidden_DisplayName
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.xxx_hidden_Password
	}
	return ""
}

func (x *CreateUserRequest) GetAssignedRoleIds() []string {
	if x != nil {
		return x.xxx_hidden_AssignedRoleIds
	}
	return nil
}

func (x *CreateUserRequest) GetActive() bool {
	if x != nil {
		return x.xxx_hidden_Active
	}
	return false
}

func (x *CreateUserRequest) GetBlockedUntil() int64 {
	if x != nil {
		return x.xxx_hidden_BlockedUntil
	}
	return 0
}

func (x *CreateUserRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *CreateUserRequest) SetTenantId(v string) {
	x.xxx_hidden_TenantId = v
}

func (x *CreateUserRequest) SetLogin(v string) {
	x.xxx_hidden_Login = v
}

func (x *CreateUserRequest) SetEmail(v string) {
	x.xxx_hidden_Email = v
}

func (x *CreateUserRequest) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = v
}

func (x *CreateUserRequest) SetPassword(v string) {
	x.xxx_hidden_Password = v
}

func (x *CreateUserRequest) SetAssignedRoleIds(v []string) {
	x.xxx_hidden_AssignedRoleIds = v
}

func (x *CreateUserRequest) SetActive(v bool) {
	x.xxx_hidden_Active = v
}

func (x *CreateUserRequest) SetBlockedUntil(v int64) {
	x.xxx_hidden_BlockedUntil = v
}

func (x *CreateUserRequest) SetMetadata(v *Metadata) {
	x.xxx_hidden_Metadata = v
}

func (x *CreateUserRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *CreateUserRequest) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

type CreateUserRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId        string
	Login           string
	Email           string
	DisplayName     string
	Password        string
	AssignedRoleIds []string
	Active          bool
	BlockedUntil    int64
	Metadata        *Metadata
}

func (b0 CreateUserRequest_builder) Build() *CreateUserRequest {
	m0 := &CreateUserRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TenantId = b.TenantId
	x.xxx_hidden_Login = b.Login
	x.xxx_hidden_Email = b.Email
	x.xxx_hidden_DisplayName = b.DisplayName
	x.xxx_hidden_Password = b.Password
	x.xxx_hidden_AssignedRoleIds = b.AssignedRoleIds
	x.xxx_hidden_Active = b.Active
	x.xxx_hidden_BlockedUntil = b.BlockedUntil
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

type CreateUserResponse struct {
	state                              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3"`
	xxx_hidden_SetInitialPasswordToken string                 `protobuf:"bytes,2,opt,name=set_initial_password_token,json=setInitialPasswordToken,proto3"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_auth_management_user_create_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_management_user_create_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateUserResponse) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *CreateUserResponse) GetSetInitialPasswordToken() string {
	if x != nil {
		return x.xxx_hidden_SetInitialPasswordToken
	}
	return ""
}

func (x *CreateUserResponse) SetId(v string) {
	x.xxx_hidden_Id = v
}

func (x *CreateUserResponse) SetSetInitialPasswordToken(v string) {
	x.xxx_hidden_SetInitialPasswordToken = v
}

type CreateUserResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id                      string
	SetInitialPasswordToken string
}

func (b0 CreateUserResponse_builder) Build() *CreateUserResponse {
	m0 := &CreateUserResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_SetInitialPasswordToken = b.SetInitialPasswordToken
	return m0
}

var File_auth_management_user_create_proto protoreflect.FileDescriptor

var file_auth_management_user_create_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x66, 0x72, 0x65, 0x79, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x1c, 0x61, 0x75, 0x74, 0x68,
	0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc1, 0x02, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c,
	0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x0f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x49,
	0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x65, 0x64, 0x5f, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x12,
	0x3b, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x66, 0x72, 0x65, 0x79, 0x6d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x61, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x3b, 0x0a, 0x1a, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x73, 0x65, 0x74, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var file_auth_management_user_create_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth_management_user_create_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: freym.auth.management.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: freym.auth.management.CreateUserResponse
	(*Metadata)(nil),           // 2: freym.auth.management.Metadata
}
var file_auth_management_user_create_proto_depIdxs = []int32{
	2, // 0: freym.auth.management.CreateUserRequest.metadata:type_name -> freym.auth.management.Metadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_auth_management_user_create_proto_init() }
func file_auth_management_user_create_proto_init() {
	if File_auth_management_user_create_proto != nil {
		return
	}
	file_auth_management_shared_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_management_user_create_proto_rawDesc), len(file_auth_management_user_create_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_management_user_create_proto_goTypes,
		DependencyIndexes: file_auth_management_user_create_proto_depIdxs,
		MessageInfos:      file_auth_management_user_create_proto_msgTypes,
	}.Build()
	File_auth_management_user_create_proto = out.File
	file_auth_management_user_create_proto_goTypes = nil
	file_auth_management_user_create_proto_depIdxs = nil
}
