name: Go Checks

on:
  push:
    branches:
      - main
    paths:
      - go/**
      - .github/workflows/go-checks.yaml
  workflow_call:

jobs:
  checks:
    name: Go Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Set up Go 1.25
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          working-directory: go
          version: latest

      - name: Check for Vulnerabilities
        uses: golang/govulncheck-action@v1
        with:
          work-dir: go

      - name: Run tests
        working-directory: go
        run: go test ./... -timeout 3m -count=1
