name: JS Checks

on:
  push:
    branches:
      - main
    paths:
      - "js/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci
        working-directory: js

      - name: Lint JS code
        run: npm run lint
        working-directory: js

      - name: Build JS libs
        run: npm run build
        working-directory: js

      - name: NPM Audit
        run: npm audit --production
        working-directory: js
