name: JS Checks

on:
  push:
    branches:
      - main
    paths:
      - js/**
      - .github/workflows/js-checks.yaml
  workflow_call:

jobs:
  checks:
    name: JS Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v5
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci
        working-directory: js

      - name: Lint JS code
        run: npm run lint
        working-directory: js

      - name: NPM Audit
        run: npm audit --production
        working-directory: js
